### PR TITLE
Add docs links for hand model

### PR DESCRIPTION
**Pull request by DavidLitwin**
I made a .rst file for the hand_calculator, and added it to the component documentation index.

### CODE REVIEW

**Comment by DavidLitwin** [comment]
Well this is odd, now it's saying there was a problem with the DOI in a different doc..

```
home/travis/build/landlab/landlab/docs/source/reference/components/chi_index.rst.rst:86:broken 
link: https://dx.doi.org/10.1002/esp.3302 (HTTPSConnectionPool(host='onlinelibrary.wiley.com', 
port=443): Max retries exceeded with url: /resolve/doi?DOI=10.1002/esp.3302 (Caused by 
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc57c9d5af0>: Failed to 
establish a new connection: [Errno -2] Name or service not known')))

Makefile:22: recipe for target 'linkcheck' failed
```

**Comment by kbarnhart** [comment]
Those DOI's sometimes have brief issues. Rebuilding usually fixes it. I can merge it if you want (yes?)

**Comment by DavidLitwin** [comment]
Alright, yes please! What I've added is pretty simple.

**Comment by kbarnhart** [comment]
Done. Thanks for adding this @DavidLitwin . You've really made a lot of valuable contributions to Landlab!

**Comment by DavidLitwin** [comment]
Thank you! I'm glad landlab is around as a platform for all of these projects. I've been having fun with it, and it's benefited my own work to have something more formal and well-documented.

**Pull request merged**
