### PR TITLE
Address depth dependent boundary conditions

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR addresses Issue #600. It covers both the DepthDependentDiffuser and the TaylorDepthDependentDiffuser. 

@Glader011235 @gregtucker can you check it out and see if it fixes the problems you are having. 

If it does I'll address failing tests and and create any necessary new ones.

### CODE REVIEW

**Comment by gregtucker** [comment]
This looks like the right fix to me. In general, components should only modify fields at core nodes, not boundaries (though there may be exceptions). 

Redefining self._active_nodes is a good way to test the fix, but if it works I think it would be clearer to remove self._active_nodes and directly use self.grid.core_nodes.

**Comment by Glader011235** [comment]
Sounds like that’ll work- I’ll let you know as soon as I test it out. 

Rachel


--
Rachel Glade
University of Colorado, Boulder
PhD Candidate
rcglade@gmail.com
rachel.glade@colorado.edu

**Comment by kbarnhart** [comment]
thanks @Glader011235 and @gregtucker 

I've cleaned up the references to core nodes and have fixed tests. 

if tests pass and @Glader011235 finds this works in her application, I'll go ahead and merge.

**Comment by Glader011235** [comment]
@kbarnhart Your fix works and keeps soil thickness constant on the boundary nodes- but unfortunately, I'm still seeing the same odd behavior in the analytical test, so there must be something else going on. Will continue trying to figure out what's going on...

That said, it would still be good to merge your changes, since we do want to avoid fluxing/weathering on the boundaries and the component should have been doing that all along (mea culpa).

**Comment by kbarnhart** [comment]
@Glader011235 I figured out your mismatch issue. Will send the notebook shortly.

**Pull request merged**
