### PR TITLE
fix: 2.0 update for docs

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR (when ready) will do the following:

- [x] Simple port of all wiki to rst and integrate with the rest of the docs
- [x] Ensure that all parts of Landlab are actually accessible in the docs
- [x] Be verified to makes sure the links work (since many are back to the wiki...)
    - [x] Remove links to wiki
    - [x] Replace hyperlinks to read the docs to sphinx page references. 
- [x] Fix broken images that existed on the wiki (e.g., examples)
- [x] Have closer to zero errors.
- [x] Move all links from nbviewer to binder (!!!)
- [x] Have zero errors
- [x] Enforce zero build errors AND zero broken links through CI

Things for the future
- [x] Update the standard name list (which gives inputs and outputs). 
- [x] ~Put binder links to tutorials in the component docstrings.~ I made Issue #1015 to handle this. 
- [x] After component PR is merged (#956) and grid PR (#997) is merged  update codebase docstrings to remove additional errors). 
 - [x] we can check for broken hyperlinks with `make linkcheck`. There are MANY broken links. @kbarnhart ~is committed to  fixing those that are NOT associated with the publications/presentations page. Those can be left for the contributors to fix on their own time.~ They are now all fixed.  
- [x] Make an issue to keep track of having someone copy edit the docs (@kbarnhart would be the 100% worst person for this job, @SiccarPoint would be good). This can be done in another PR. 

See the docs [here](https://landlab.readthedocs.io/en/barnhark-bring_wiki_to_docs/).

### CODE REVIEW

**Comment by SiccarPoint** [comment]
This looks like heroic work! And very sensible. Can proof this in about 2 weeks, but probably not really before that? Also, happy to try to figure out a way to automate the building of the standard names list. I nearly had this at one point, and shouldn't be hard.

**Comment by kbarnhart** [comment]
Thanks @SiccarPoint . There will definitely be a moment for copyediting that will occur independent of this PR. I'm the world's worst copyeditor, so I'll definitely take you up on looking at it. 

I have a plan for the standard names list...!

**Comment by kbarnhart** [comment]
@SiccarPoint see the revised component listing here:
https://landlab.readthedocs.io/en/barnhark-bring_wiki_to_docs/user_guide/field_io.html

I've written a script to automate making it, just haven't done the bit where the automated output gets placed in the right place with every build.

**Comment by kbarnhart** [comment]
@mcflugen I may need your help for the last of the errors...

We have three remaining... And I do not understand them (as `Component.name` exists, and does not have 12 lines).

```bash
WARNING: failed to import landlab.core.model_component.Component.name
/Users/barnhark/projects/landlab/landlab/landlab/core/model_component.py:docstring of landlab.core.model_component.Component.name:12: WARNING: Unexpected indentation.
/Users/barnhark/projects/landlab/landlab/landlab/core/model_component.py:docstring of landlab.Component.name:12: WARNING: Unexpected indentation.
```

**Comment by kbarnhart** [comment]
@mcflugen I've pushed my current commits. I've dealt with most of the `CLOSED_BOUNDARY` instances (but probably not all).

I suspect that our check will be when all of the BC flags have been removed from the `__init__.py` files for both landlab and landlab.grid.

I'm going to pause on pushing to this branch for a moment, and let you work on the very last of the sphinx warnings and these BC flags.

**Comment by kbarnhart** [comment]
@mcflugen I can reproduce [the error](https://travis-ci.org/landlab/landlab/jobs/599696764#L1790) locally, but am not sure how to fix it...

**Pull request merged**
