### PR TITLE
Add nuke and requirements sessions to the noxfile

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds two new sessions to the *landlab* *nox* file: *requirements* and *nuke*. The *requirements* session creates the various requirements files from the requirements listed in *pyproject.toml* (by running the *requirements.py* script). The *nuke* session is intended to *really* clean up a working repository by running the *clean* session followed by removing *jupyter* notebook checkpoint directories.

Examples:
```
$ nox -s requirements  # recreate requirements.txt, requirements-docs.txt, etc.
$ nox -s nuke  # really clean the entire repository
$ nox -s nuke -- landlab tests  # only run on the landlab and tests folders
```

### CODE REVIEW

**Comment by sebastien-lenard** [comment]
@mcflugen I'm a bit confused. Is there any doc on nox and how to use it within the landlab dev environment?

**Comment by mcflugen** [comment]
@sebastien-lenard I think the best place to look for using *nox* is probably just their [main documentation](https://nox.thea.codes).

For your *landlab* development, you may (or may not) find the following useful:
* Run all of the tests in an isolated environment,
```bash
$ nox -s tests
```
* Check for lint,
```bash
$ nox -s lint
```
* Remove auto-generated files (`*.pyo`, `__pycache__`, `*.so`, etc),
```bash
$ nox -s clean
```
* Clean as above but also remove notebook checkpoints, running only in the *landlab* folder,
```bash
$ nox -s nuke -- landlab
```

**Comment by sebastien-lenard** [comment]
Alright @mcflugen. So if I have a problem with notebook checkpoints in my landlab dev, I can run 
```
$ nox -s nuke -- landlab
```
and then 
```
python setup.py build_ext --inplace
```
without having problem with these hidden .ipynb files ? #1461 #1467

But does 
```
$ nox -s nuke -- landlab
```
also removes all compiled files? because I don't want to recompile everything each time I want to compile one file to test it ...

**Comment by mcflugen** [comment]
> also removes all compiled files?

It does because that's sometimes something we want to do. However, we can certainly add a new session or modify the existing ones to do different tasks.

**Comment by mcflugen** [comment]
@sebastien-lenard I'll update this pull request with some reorganization of the cleaning sessions to include your use case.

**Comment by sebastien-lenard** [comment]
Hi @mcflugen 
these notebook entrypoints are also created in the docs (on the Jupyter hub), I don't know why ...

- docs/source/reference/.ipynb_checkpoints/
- docs/source/development/install/.ipynb_checkpoints/
- docs/source/.ipynb_checkpoints/

**Comment by mcflugen** [comment]
I've included some additional changes in the pull request,
* removed more lint, this time mostly in *pyx* files
* changed our ci to use *nox*
* added two new linters: one that runs *pyroma* and one that runs *check-manifest* (which was inspired from @mdpiper's recent pull request #1534)

@mdpiper Would you mind having a look at this when you get a chance?

**Review by mdpiper — APPROVED** [review]

**Comment by mdpiper** [comment]
👍

**Pull request merged**
