### PR TITLE
Link status overhaul

### PR DESCRIPTION
**Pull request by jadams15**
This pull request will merge all changes from the link_status branch into the master branch of our repository. Main changes include:

New link boundary condition functionality. In addition to active_links (link_status==0), and inactive_links (link_status==4), we now have fixed_links (link_status==2) where values at links can be set or changed dynamically as a boundary condition. 

Base.py has a set_nodata_nodes_to_fixed_gradient() function. Raster.py has set_fixed_link_boundaries_at_grid_edges() function. 

Updates have been made to boundary condition handling to ensure that all links adhere to the following rules:
Active links occur between two core nodes (node_status==0). Inactive links occur between closed nodes (node_status==4) and any other node type (node_status==0,1,2,4). Fixed links occur between a core node (node_status==0) and a fixed gradient boundary node (node_status==2).

Neighbor boundary finding now has d4 and d8 methods (before it just had d8, which is still the default).

Links.py was updated to contain fixed_link_ids(), is_fixed_link() horizontal_fixed_link_ids(), vertical_fixed_link_ids(). 

All doctests were updated to match new conventions as well. As of this pull request all doctests are passing in Travis.

### CODE REVIEW

**Comment by mcflugen** [comment]
Looks good. Some tests are failing on 64-bit Windows but they shouldn't be too hard to fix. I'll take a crack at it.

**Comment by jadams15** [comment]
Thanks Eric. Looks like those pesky dtype errors I know we were having a while back. Let me know if there is anything I can do to help.

**Comment by mcflugen** [comment]
Some docstrings need cleaning up. I updated the docstring for `set_nodata_nodes_to_fixed_gradient` but some others will need a bit of love, too (``set_nodata_nodes_to_closed``, for example).

For docstrings to render properly:
* The docstring header for examples must be ``Examples``
* Text that is to be displayed verbatim (a diagram of a grid, for example) should be in an indented block that's preceded by ``::``.

Other changes:
* Added cross-references for some objects. I used the ``any`` role for this. I don't know if that was the best way but it was convenient.
* Reformatted some doctests as the lines were too long to read. I hope they're a little clearer now.

If you want to build the docs locally to check how things look:

```bash
    $ cd docs
    $ make html
    $ open _build/html/index.html
```

**Comment by jadams15** [comment]
Ok. I'll get to work on these ASAP. Will I need to submit a new pull request after the edits are done?

**Comment by mcflugen** [comment]
Nope. No new pull request. Any changes you push to **link_status** will show up here.

**Comment by mcflugen** [comment]
I added just a few more commits.
* Fixed a few failing tests on Windows and Python 3
* Added some PEP8 stylings

**Pull request merged**
