### PR TITLE
Update install commands to include channels

### PR DESCRIPTION
**Pull request by mcflugen**
### Description

This pull request updates the *conda*/*mamba* installation commands in the docs to explicitly include channels. Since some of *Landlab*'s dependencies are not available in the default *conda* channel, it's important to tell *conda* to look to *conda-forge* for packages (see #1704). If someone doesn't have *conda-forge* in their *.condarc* file, packages from *conda-forge* won't be seen and users will see a ``PackagesNotFoundError``.

As there can be incompatibilities with packages from the default channel and from *conda-forge*, it's good practice to ensure that all packages come from *conda-forge*. Thus, the install command now looks like,
```
conda install --file=requirements.in -c nodefaults -c conda-forge --override-channels
```
This tells conda to look at *conda-forge*, ignore the default channel, and override any channel settings a user may have in their config file.

### Checklist - did you ...

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by mcflugen** [comment]
@pfeiffea when you have time, would you please give this pull request a look over and see if it makes sense to you? And that it works!

**Review by pfeiffea — APPROVED** [review]
This looks great. Just ran successfully on my machine. 

Thanks @mcflugen

**Comment by mcflugen** [comment]
@pfeiffea In #1700 you also had an issue with your C++ compiler. When building Python extensions (as we do when building *Landlab*), one must have a C++ compiler installed. This is true of any operating system but it seems to be most commonly an issue for Windows users (as you experienced). Since this is somewhat outside of a *Landlab* issue, and since it can be a moving target, we don't have anything about it on our docs. It would be nice, however, if we could point users to some online resources that describe how to install and set up their compilers. The best that I've found is buried in the [*conda-forge* docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#notes-on-native-code) and on the [Python wiki page for Windows compilers](https://wiki.python.org/moin/WindowsCompilers). Would those have been helpful to you? Did you find anything online you found helpful that maybe we could point users to?

**Comment by pfeiffea** [comment]
@mcflugen I ended up using the python wiki page you linked above, and the error that popped up in the command prompt sent me to the correct C++ compiler install page. That was totally sufficient. 

I think a simple mention in the install instructions that (especially Windows) users may need to install updated C++ compilers would be a simple, but substantial help. I've run into this every time I've set up a new computer (or re-set up a computer after wiping). I seem to remember there was mention of this step on the old docs page, so I wondered if it was no longer a necessary step when I didn't see it mentioned this time.

**Comment by mcflugen** [comment]
@pfeiffea I've added text about compilers that also includes a couple links to resources for Windows users.

I've tried to balance saying enough to be helpful but not saying too much, which could make the process seem difficult, include information that could become dated, or repeat instructions that are already elsewhere on the internet.

@gantian127, @gregtucker Any thoughts?

**Comment by gantian127** [comment]
@mcflugen I did a test for the source install of landlab on windows system. I mainly tested the conda commands and it worked. Only one comment is for the git clone command in the documentation. When using the link, it will show error info (fatal: unable to connect to github.com). It may be better to change the link as https://github.com/landlab/landlab.git.  Thanks!

**Comment by mcflugen** [comment]
Thanks @gantian127!

I've changed the installation page to include commands to clone the repository through ssh (with the correct address!) and https.

**Pull request merged**
