### PR TITLE
Address unexpected network model grid error

### PR DESCRIPTION
**Pull request by kbarnhart**
Error documented in #855

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen it looks like all the appveyors are still erroring-out. And doing so by trying to downgrade from py37 to py36... I'm not quite sure why. I added a pyshp dependency, but it is 3.x compatible.

**Comment by kbarnhart** [comment]
@mcflugen looks like conda-build=3.0 is necessary for <py3.6

I think we should try a conditional. I just don't know how to correctly write something like 

```
  - cmd:  |
       if (%CONDA_PY% -eq "37")
       {conda install -q conda-build=3.0}
       else {conda install -q conda-build}

```
in the appveyor syntax...

**Comment by mcflugen** [comment]
@kbarnhart I think we should just drop Python 3.5. *conda-forge* only uses Python 2.7, 3.6, and 3.7.

**Comment by kbarnhart** [comment]
sounds good to me.

**Comment by kbarnhart** [comment]
I think we already dropped 3.5

**Comment by kbarnhart** [comment]
@mcflugen 

Looks like the appveyor builds now all error on

```
%WITH_COMPILER% conda build -q .conda-recipe --old-build-string
```
```
Packaging landlab
2654INFO:conda_build.build:Packaging landlab
2655Packaging landlab-1.6.0+103.g6137e7ff-0
2656INFO:conda_build.build:Packaging landlab-1.6.0+103.g6137e7ff-0
2657No files or script found for output landlab
2658WARNING:conda_build.build:No files or script found for output landlab
2659Traceback (most recent call last):
2660  File "C:\Miniconda\Scripts\conda-build-script.py", line 10, in <module>
2661    sys.exit(main())
2662  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 456, in main
2663    execute(sys.argv[1:])
2664  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 447, in execute
2665    verify=args.verify, variants=args.variants)
2666  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 208, in build
2667    notest=notest, need_source_download=need_source_download, variants=variants)
2668  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2311, in build_tree
2669    notest=notest,
2670  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1628, in build
2671    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
2672  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 942, in bundle_conda
2673    "info." .format(dep, link))
2674conda_build.exceptions.CondaBuildException: Empty package; python dep present in build but not host requirements.  You need to move your python dep to the host requirements section.  See https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host for more info
```

The [part of conda docs](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host) referenced in the error recommends moving python from the build section to the host section of the meta.yaml. So I've now done this... we will see if it works...

**Comment by mcflugen** [comment]
@kbarnhart Yes, that is correct, it should be in a different section (I think the only thing in the build section should be the c compiler). I guess I never changed it because we were using an old *conda-build*. Anyway, you may want to have a look at the *meta.yaml* I created for our [*conda-forge* recipe](https://github.com/conda-forge/landlab-feedstock/blob/master/recipe/meta.yaml). Ours here should, pretty much, match that one.

**Comment by kbarnhart** [comment]
@mcflugen these changes worked for `branch`. So I think they should work for `pr`. 🎉

**Pull request merged**
