### PR TITLE
inits for Hybrid Alluvium

### PR DESCRIPTION
**Pull request by cmshobe**
made/edited __init__ files for Hybrid Alluvium component @kbarnhart

### CODE REVIEW

**Comment by kbarnhart** [comment]
@cmshobe it looks like you have some python 2-python 3 compatibility issues (only 3.5 and 3.6 fail). You can either create a python3 environment on your computer for testing or we can use my computer. 

In the builds I look at I see the following error:
```
DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  flooded = self._grid.nodes.flatten() == flooded_nodes
```
and the log is truncated so I can't see the full reason the component failed. 

This error often occurs if broadcasting must be done for the comparison. 

Looking at your unit tests it looks like flooded nodes is an array of node IDs that are flooded, constructed by np.where(). In the above lines it is being used as a boolean array of length number_of_node.

**Comment by kbarnhart** [comment]
ahh. I see you can download the full log file.

**Comment by mcflugen** [comment]
It looks to me like you are trying to do a relative import in Python 3 but imports in Python 3 default to absolute. In your doctest for `HybridAlluvium` you have
```python
from hybrid_alluvium import HybridAlluvium
```
This should be
```python
from landlab.components import HybridAlluvium
```
The reason this works in Python 2 is that the doctest is run in the same folder as `hydrid_alluvium.py`. Doctest should always be written as examples to show how an end user would run your component.

**Comment by cmshobe** [comment]
Thanks @kbarnhart and @mcflugen ! I've fixed the deprecated == and also the doctest import statement; we'll see if there's anything else

**Comment by mcflugen** [comment]
Your tests are failing for your deprecation fix. I'm not totally sure what you are wanting to do so this might not be the most efficient way of doing it but instead of,
```python
flooded = np.equal(self._grid.nodes.flatten(), flooded_nodes)
```
something like the following should work,
```python
flooded = np.full(grid.number_of_nodes, False, dtype=bool)
flooded[flooded_nodes] = True
```

**Pull request merged**
