### PR TITLE
RiverBedDynamics - new component

### PR DESCRIPTION
**Pull request by angelmons**
### Description
Add RiverBedDynamics Component & Update overlandFlow to Support Variable Roughness and Rainfall Intensity

This PR introduces a new component, RiverBedDynamics, designed to calculate sediment transport and river bed evolution.

In addition to this, we've made necessary modifications to the overlandFlow component to support spatially variable roughness and rainfall intensity. These new features enhance its flexibility, allowing users to define spatially variable parameters at the time of instantiation. If these parameters are not specified, overlandFlow defaults to using uniform values, preserving the behavior of its previous version.

### Checklist - did you ...

- [ ] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [X ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?
- [X ] All tests have passed?
- [X ] Formatted code with black?
- [X ] Removed lint reported by flake8?
- [ ] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by gregtucker** [comment]
@angelmons thanks for submitting this PR! Do you have any suggestions on who might be a good external reviewer (i.e., apart from folks at the CSDMS Integration Facility, at least one of whom will review this)? Maybe one of your collaborators who hasn't seen the code before?

**Comment by nicgaspar** [comment]
Hi @gregtucker I already did a "pre-review" of Angel's code. By that I mean when he had everything finished and working, I went through it all to check if it was Landlab style and generally checked his approach in coding up the different algorithms. We did that informally though, so there is no GitHub record.

**Comment by gregtucker** [comment]
That's great! In that case, one of us here can take a look, I don't think another outside look would be needed. It's a big PR so please be patient :)

**Comment by gregtucker** [comment]
@angelmons it looks as if some of the lint tests are failing. You can see details of the failing lint tests by clicking the above "Details" button under "Lint / Check for lint" above. These should be easy to fix. Run "black" on your code (just "black <filename>" on the command line; you'll have to conda install it if it isn't already there). That should automatically take care of most of it. Run isort (same procedure), which will rearrange order of imports if needed. Finally, run flake8. Unlike the other two, flake8 won't make changes for you, but it will identify places that need attention. For your tutorial notebook, black-jupyter is a great tool. There are a couple of ways to use it; I found the easiest was to install the add-on tool for the Jupyter app, so I get a little "black" button at the top of the notebook, and clicking it automatically lints the notebook code.

**Comment by mcflugen** [comment]
@angelmons To make finding and removing lint even easier, I suggest using *nox*. We have a brief description of this on our [developer docs](https://landlab.readthedocs.io/en/master/install/developer_install.html#developer-tools).

Basically, install *nox* (``pip install nox``) and then run ``nox -s lint``.

**Comment by mcflugen** [comment]
@angelmons Thank you for your contribution!

Since I've been working on cleaning up and speeding up *OverlandFlow* (in #1627), I can have a look at your pull request.

A couple things I noticed (apart from the failing tests),
* Your pull request is from the *master* branch of your fork. Best practice is to always work on a topic branch and initiate a pull request from that branch. When the pull request is from your *master* branch, it makes it a little more difficult on our side but, more importantly, it could cause issues on your end when syncing your fork in the future.
* The `OverlandFlow` component already supported spatially variable roughness and rainfall intensity. Both the *rainfall_intensity* and *mannings_n* keywords are supposed to handle scalars or arrays.
* You've changed some of the field names that *OverlandFlow* uses (e.g. *water_surface__gradient* to *surface_water__gradient*). I think I see why you've done this but, although it makes sense, this change will break existing code that uses *OverlandFlow*.
* Along the same lines, changing the *rainfall_intensity* keyword to *rainfall__intensity* will break existing code.

**Comment by angelmons** [comment]
Hello @mcflugen, @nicgaspar, and @gregtucker,

Thank you for your valuable feedback and guidance. I believe I can address all of the points you've both brought up, especially those noted by @mcflugen. Incorporating these changes will undoubtedly simplify the component, which is fantastic.

Given the substantial changes that will be made, would you suggest closing this current pull request and then opening a new one once everything has been addressed? Please let me know what you think would be the best approach.

I look forward to your advice. Thanks again for your help.

**Comment by gregtucker** [comment]
@angelmons you don't need to close the PR (it's fine to re-open it), just flag it as a draft for now and you can push changes as you revise. Then when ready hit the "Ready for review" button (which appears when you flag a PR as a draft). In the meantime, if you have a push but don't need all the tests to run, if you include "[no ci]" in the commit message the tests will be skipped for that push.

**Pull request closed without merging**
