### PR TITLE
Add output in legacy VTK format

### PR DESCRIPTION
**Pull request by gregtucker**
### Description

This PR provides a new io function called `write_legacy_vtk`, which outputs in legacy VTK unstructured grid format to a file-like object. The PR was motivated by the need to visualize hex grids in ParaView. Addresses issue #1643.

### Checklist

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [X] Add / update tests if necessary?
- [X] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Successful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by gregtucker** [comment]
Oddly, 2 test runs passed and one failed. The test fails seem unrelated to this PR:

```
FAILED landlab/io/netcdf/dump.py::landlab.io.netcdf.dump.to_netcdf
FAILED landlab/io/netcdf/write.py::landlab.io.netcdf.write.write_netcdf
FAILED landlab/io/netcdf/write.py::landlab.io.netcdf.write.write_raster_netcdf
FAILED landlab/components/flow_accum/flow_accumulator.py::landlab.components.flow_accum.flow_accumulator.FlowAccumulator.link_order_upstream
FAILED landlab/components/flow_director/flow_director_dinf.py::landlab.components.flow_director.flow_director_dinf.FlowDirectorDINF
FAILED landlab/graph/matrix/at_node.py::landlab.graph.matrix.at_node.get_links
FAILED landlab/graph/sort/sort.py::landlab.graph.sort.sort.argsort_spokes_at_hub_on_graph
FAILED tests/grid/unstructured/test_links.py::test_links_3x3_quad
```

Perplexity :|

**Comment by mcflugen** [comment]
@gregtucker I've noticed these failures as well in other pull requests. I suspect they has something to do with a recent update to one of our dependencies.

**Comment by mcflugen** [comment]
@gregtucker It looks like these errors are due to a *numpy* update (v1.25). The v1.25 release notes list speed improvements to *np.sort* and *np.argsort*, which appear to be the two functions that are causing our tests to fail.

In #1645 I've limited *numpy* to less than 1.25 and the problem goes away. Not a great solution but perhaps good enough for now?

**Comment by gregtucker** [comment]
The test fail seems to be unrelated to this PR. Could @mcflugen and/or @gantian127 and/or @mdpiper take a look at this?

**Comment by mdpiper** [comment]
It looks like a cell timed out in a notebook. I'll run the test again to see if it's a transient.

**Comment by mcflugen** [comment]
> It looks like a cell timed out in a notebook. I'll run the test again to see if it's a transient.

It is. It seems to occur about half the time, unfortunately. I keep meaning to dig into it to see what's going on and try to fix it.

**Comment by mdpiper** [comment]
The test failed again, but on a different notebook.

First time:
```
FAILED notebooks/tutorials/network_sediment_transporter/sediment_pulser_at_links.ipynb
```

Second time:
```
FAILED notebooks/tutorials/flow_direction_and_accumulation/PriorityFlood_realDEMs.ipynb
```

**Comment by gregtucker** [comment]
This PR is getting a bit stale... I just updated with latest master. Anyone available to review it? If no takers, I'll merge it myself if tests pass.

**Comment by mdpiper** [comment]
I'll take a look right now.

**Review by mdpiper — APPROVED** [review]
Looks good! I'm surprised a general legacy VTK writer doesn't already exist. (Whoops, wait, I shouldn't volunteer for this!)

**Comment by gregtucker** [comment]
The one test fail is unrelated to this PR, so I'm merging.

**Pull request merged**
