### PR TITLE
Barnhark/make map upwind node to link

### PR DESCRIPTION
**Pull request by margauxmouchene**
Addresses issue #711:
Create a mapper that assigns a value to a link from its upstream node.

### CODE REVIEW

**Comment by SiccarPoint** [comment]
I believe this method duplicates existing functionality. See `map_max_of_link_nodes_to_link`. Consider junking it, unless you're happy it's different enough.

**Comment by kbarnhart** [comment]
@gregtucker and recently discussed this. 

Based on that discussion, I think what we want may be 

`map_value_at_upwind_node_to_link(grid, control_name, value_name)`
and 
`map_value_at_downwind_node_to_link`(grid, control_name, value_name)`

In which upwind vs downwind is determined by `control_name` (so we could use `topographic__elevation` to have the effect of doing this based on flow direction). 

And `value_name` represents the value to map to links. 

We don't currently have these mappers, but they would be generic than what @margauxmouchene and I cooked up yesterday, but would map from nodes to links. 

Also, as links only have one node on either end of them, we don' need to think about the min/max/mean of the upwind/downwind values as we we do for the map upwind link to node-type mappers.

**Comment by SiccarPoint** [comment]
(I believe when these were made we were not using "upwind"/"downwind", for consistency with wider-spread use of "min"/"max" elsewhere in the code base, and also because those terms are clearer if you aren't already familiar with the jargon.)

**Comment by kbarnhart** [comment]
@SiccarPoint , thanks for clarifying, You are right, that function is what we want. 

I will think about how (if at all) I might think about revising the mappers documentation section in order to make sure that I would have been about to figure this out based on the documentation alone).

**Comment by SiccarPoint** [comment]
Yes, we need to work on that! I got here by:
1. Being pretty sure we had such a thing in the first place, then
2. Instantiating a grid, then doing `grid.map_[tab]` in iPython.
This is not a particularly advisable workflow for a user in the wild!

**Comment by kbarnhart** [comment]
@SiccarPoint @margauxmouchene I just had a further thought... Sometimes the elevation differences are not sufficient to map based on flow (e.g. when there is a depression). 

Option A) A user/developer needs to be savvy enough to figure out that they should use `map_value_at_max_node_to_link(control_name, value_name, out=None)` on a pit filled field, or 

Option B) We make something like this that is flow-routing specific. 

I'm pretty split between these two. Do either of you have opinions?

**Comment by SiccarPoint** [comment]
For a grid method, I think we should keep it simple. Maybe add a router-specific alternative as part of the routing tool sets?

**Comment by kbarnhart** [comment]
I'm closing this issue since I think @SiccarPoint resolved it in the spring.

**Pull request closed without merging**
