### PR TITLE
Improvements on GDP

### PR DESCRIPTION
**Pull request by DavidLitwin**
Repeat of #1038, only from branch on landlab/landlab. Math is better formatted in the docstring of the GroundwaterDupuitPercolator, more setters and getters are added, check water table elevation above land surface elevation, and the begin files for the JOSS paper.

### CODE REVIEW

**Comment by mcflugen** [comment]
@DavidLitwin If you're interested, your docs for *GroundwaterDupuitPercolator* are now building on [readthedocs](https://landlab.readthedocs.io/en/dlitwin-gdp_joss/landlab.components.html#landlab.components.GroundwaterDupuitPercolator). They look great!

Thank you for your contribution! 🎉

**Comment by kbarnhart** [comment]
Thanks for turning the docs on @mcflugen!

**Comment by DavidLitwin** [comment]
@mcflugen I'm having trouble getting my figures to show up [here](https://landlab.readthedocs.io/en/dlitwin-gdp_joss/dupuit_theory.html#theory-and-implementation-of-groundwaterdupuitpercolator) from the file  dupuit_theory.rst... If you have a chance, could you take a look? I've tried a number of things from the Sphynx documentation and stackexchange, but nothing has worked so far. Thanks!

**Comment by mcflugen** [comment]
@DavidLitwin I suspect it's just a typo. In the *rst* file you refer to *water_table_schematic.PNG* but the actual file in the images folder is called *water_table_schematic.png* (lowercase *png* extension).

**Comment by DavidLitwin** [comment]
@mcflugen As it's showing for me, the reference to the file is listed with '.png' now. I think there was an early commit where that was the case, but I believe I fixed it.

**Comment by DavidLitwin** [comment]
Both images appear when I build it locally (though neither are centered, as they should be), but the readthedocs build is still missing the first figure.

**Comment by mcflugen** [comment]
@DavidLitwin The build of the docs on *readthedocs* is giving the warning,
```
WARNING: image file not readable: images/water_table_schematic.png
```
Did you change the name of the image file on the remote repository or maybe just locally? On GitHub, the image file is [*images/water_table_schematic.PNG*](https://github.com/landlab/landlab/tree/dlitwin/gdp_joss/docs/images) but [*docs/dupuit_theory.rst*](https://github.com/landlab/landlab/blob/dlitwin/gdp_joss/docs/dupuit_theory.rst) on GitHub uses the lowercase extension.

**Comment by DavidLitwin** [comment]
@mcflugen Ah! That's it. I guess gitkraken missed the change in capitalization.

**Pull request merged**
