### PR TITLE
Merge master into release for v2.0.0 

### PR DESCRIPTION
**Pull request by kbarnhart**

### CODE REVIEW

**Comment by kbarnhart** [comment]
@nathanlyons could you please resolve the species evolution related merge conflicts? I don't know what correct is...

**Comment by nathanlyons** [comment]
@kbarnhart Resolved all SpeciesEvolver conflicts. One for groundwater remains. The 'master' portion was correct for all of the SpeciesEvolver.

**Comment by kbarnhart** [comment]
@nathanlyons thanks for that. It didn't seem to save my prior change on the groundwater component code. And it didn't seem to save your changes. So I handled the merge conflicts locally by merging `release` into `master` and selecting the master version where those conflicts existed. 

You can see that commit [here](https://github.com/landlab/landlab/pull/1187/commits/ae600a869e7cb047e0d0cce21f658266b811a07d) and the fact that no files are changed means (I think) that I successfully selected the `master` versions of all conflicts. 

I did a final run of make pretty [here](https://github.com/landlab/landlab/pull/1187/commits/abce5d4145fad6df79a6d982c09dd8bccda79cca).

(@mcflugen Sorry for committing directly to master... but it seemed like this is one of the few times it was appropriate)

@nathanlyons If you see anything wrong with how I've handled this, let me know. 

Presuming this passes, I'll move forward with creating our final v2.0.0 release 🦖

**Comment by nathanlyons** [comment]
@kbarnhart All related to species evolver looks correct with one minor exception. A folder in `joss` at the same level of `publications` is the in-review species_evolver paper folder that should be deleted. Inside `publications` is the final species_evolver paper materials that should remain.

Leviosa, v2.0.0

**Comment by kbarnhart** [comment]
@nathanlyons thanks! I removed this. It is correct now, right?

**Comment by nathanlyons** [comment]
It is! :tada:

**Pull request merged**
