### PR TITLE
fix: imshowgrid in v2

### PR DESCRIPTION
**Pull request by kbarnhart**

### CODE REVIEW

**Comment by kbarnhart** [comment]
Addresses #1048

**Comment by kbarnhart** [comment]
@mcflugen this is the branch to take over on.

**Comment by mcflugen** [comment]
@kbarnhart will you please have a look at this and let me know if it's working as you expect? I'm able to plot values located at cells of a *HexModelGrid* so, if it's not completely working, it's probably pretty close.

**Comment by kbarnhart** [comment]
@mcflugen it almost works now...

The remaining thing to fix (I tried... but haven't finished... would be great if you could take a stab) is that color-for-closed doesn't presently work for for irregular grids. 

The last plot on "tutorials/boundary_conds/set_BCs_on_voronoi.ipynb" is a good example. 

https://github.com/landlab/tutorials/tree/v2_dev has the tutorials on it. 

Except for the component making tutorial and the two eco hydro everything now passes :)

**Comment by mcflugen** [comment]
@kbarnhart That's great! 🎉 Thanks for your help. I'll take a stab at the rest tonight.

**Comment by kbarnhart** [comment]
Thanks @mcflugen. If you end up thinking that it is worth adding show_elements back because the voronoi plots look weird.... probably easiest to add a LineCollection that shows all of the edges....

**Comment by mcflugen** [comment]
@kbarnhart I've added back all the edges. I'm not sure if it's exactly the same as *show_elements* or not but the plots do look better.

I've fixed the *color_for_closed* issue but found a new problem when plotting a field defined at cells. It should be an easy fix.

**Comment by mcflugen** [comment]
@kbarnhart could you have another look? I think it's all fixed now. I made a few changes,
* set cell edges to be black lines
* fixed issue with the face color of cells of closed boundary nodes
* fixed plotting of fields defined at cells
* changed *vmin*, *vmax* to be min/max over all values being plotted

**Comment by kbarnhart** [comment]
@mcflugen other than setting the default to have black outlines, your changes look great.

This is because when you are plotting a small grid, sometimes you want to see the edges... other times, I don't want to see the edges...

I added back the `show_elements` option, and implemented it with a line collection. It plots the faces.

Its not 100% the same as the prior option (which showed the "half faces" extending away from the grid in between the nodes that don't have cells). I don't think its critical to put that back. 

Assuming this passes, I'll merge it.

**Comment by kbarnhart** [comment]
@mcflugen how do you make a new release on the `conda-forge/label/dev` channel?

Once this and #1053 are merged, I'd like to make a new release so I can test the v2_dev branch notebooks on binder. 

I assume the next version is `v2.0.0b1`, right?

**Comment by mcflugen** [comment]
@kbarnhart On your fork of *conda-forge/landlab-feedstock*
* checkout the *devel* branch
* create a new branch for *v2.0.0b1*
* update *meta.yaml*
* create a pull request to merge back into ***devel*** (it's important to merge it back into *devel*, not *master*)

**Pull request merged**
