### PR TITLE
Add load/dump functions for ESRI ASCII files

### PR DESCRIPTION
**Pull request by mcflugen**
### Description

It would be nice if *Landlab* functions to read/write to various data formats followed a standard interface. This pull request adds load/dump functions for the ESRI ASCII format. These are similar to those for VTK. The new functions also have some enhanced capabilities like being able to load data from a file and place it on different grid elements (i.e. nodes, corners, cells or faces), not just nodes (#1947).

### Checklist - did you ...

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Review by mdpiper — APPROVED** [review]
I think this is great! One comment: would it make sense to use the idiom `esri_ascii.load` instead of `load`, akin to `yaml.load` or `toml.load` (and the same for `dump`)? I think it makes it more transparent what sort of file is being read/written.

**Comment by mcflugen** [comment]
> I think this is great! One comment: would it make sense to use the idiom `esri_ascii.load` instead of `load`, akin to `yaml.load` or `toml.load` (and the same for `dump`)? I think it makes it more transparent what sort of file is being read/written.

Thanks @mdpiper! Do you just mean in the examples and notebooks to use something like,
```python
from landlab.io import esri_ascii

with open(file) as fp:
    grid = esri_ascii.load(fp)
```

**Comment by mdpiper** [comment]
@mcflugen Yup! Just in the examples & notebooks. (I'm still thinking about LL coding style.)

**Comment by mcflugen** [comment]
> @mcflugen Yup! Just in the examples & notebooks. (I'm still thinking about LL coding style.)

Great. I've made those changes.

What do you think if I deprecate the old functions and move them to another module? I'm thinking moving them to a private module called `_deprecated_esri_ascii.py` and a user would import them as they can do now (i.e. `from landlab.io import read_esri_ascii`)?

**Comment by mdpiper** [comment]
> What do you think if I deprecate the old functions and move them to another module? I'm thinking moving them to a private module called `_deprecated_esri_ascii.py` and a user would import them as they can do now (i.e. `from landlab.io import read_esri_ascii`)?

I think this a great idea because it'll help with backward compatibility.

**Pull request merged**
