### PR TITLE
Fixed reference in PriorityFloodFlowDirector

### PR DESCRIPTION
**Pull request by BCampforts**
The main change in this PR is to fix a broken reference in the PriorityFloodFlowDirector where the gradients of the hillslopes are being updated. A second fix is to resolve instabilities related to the use of very small H* values when using the "Space_Large_Scale_Eroder". Some other cosmetic changes and added control on location of ylabels of colorbars in imshowhs_grid function. @mcflugen this is a minor change compared to the previous PR, mainly fixing some minor issues.

### CODE REVIEW

**Comment by mcflugen** [comment]
Thanks @BCampforts! Will you please create a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html?highlight=News#news-entries) for the changelog?

**Comment by mcflugen** [comment]
@BCampforts It looks like you removed blank lines from the files you edited. I think, for the most part, we probably want them back—particularly as paragraph separators in the docstrings.

**Comment by BCampforts** [comment]
> 

Yup, working on it

**Comment by BCampforts** [comment]
> Thanks @BCampforts! Will you please create a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html?highlight=News#news-entries) for the changelog?

I added files to the news/ directory, @mcflugen will they be automatically integrated in changelog?

**Comment by mcflugen** [comment]
> I added files to the news/ directory, @mcflugen will they be automatically integrated in changelog?

Yes, they'll be added with the next *landlab* release. Thanks!

**Comment by BCampforts** [comment]
There seems to be an issue with the notebooks for macos-latest, 3.8. It has to do with the RichDEM package. Can you have a look at this @mcflugen? Thanks!

**Comment by BCampforts** [comment]
> There seems to be an issue with the notebooks for macos-latest, 3.8. It has to do with the RichDEM package. Can you have a look at this @mcflugen? Thanks!

#1399 solved this. Thanks @mcflugen!

**Comment by mcflugen** [comment]
@BCampforts you've removed a lot of blank lines from several files. Could you please add them back—particularly in the docstrings  where they serve as paragraphs separators.

**Review by mcflugen — APPROVED** [review]
👍

**Pull request merged**
