### PR TITLE
Keep sediment__influx values in SpaceLargeScaleEroder

### PR DESCRIPTION
**Pull request by gregtucker**
### Description

The `SpaceLargeScaleEroder` component has a `sediment__influx` field that tracks the volume rate of sediment entering each grid node. However, the values on core nodes are zeroed out in the main loop. This PR provides a potential solution.

As far as I can tell, the zeroing out is done to facilitate calculating the volume of sediment leaving the river(s) in each time step, where "leaving" means entering an active boundary node. By zeroing out every sediment-influx value BUT those on boundary nodes, the return of this summed calculation can be done by just summing up all the sediment influx values. This PR proposes an alternative approach: only sum sediment influx values on boundary nodes. Values on closed boundary nodes should always be zero, so in effect this amounts to adding up the values on open boundary (i.e., fixed value) boundary nodes. Doing it this way means it is no longer necessary to zero out the sediment influx value at each core node as it is processed, so the influx field is preserved for other components to use, or for further analysis and/or plotting.

This addresses issue #1638.

### Checklist

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [X] Add / update tests if necessary?
- [X] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Successful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by gregtucker** [comment]
The test fail seems unrelated to this PR. Could @BCampforts take a look when you get a chance? @loroberge needs this for his "concentration tracking" component.

**Comment by BCampforts** [comment]
> The test fail seems unrelated to this PR. Could @BCampforts take a look when you get a chance? @loroberge needs this for his "concentration tracking" component.

It's on my radar @gregtucker, will have a look sometime this week.

**Comment by mcflugen** [comment]
@BCampforts Do you have any thoughts on this pull request? If it's good to go, I would like to include it with the forthcoming 2.7 release (tomorrow?).

**Review by mcflugen — APPROVED** [review]
👍

**Pull request merged**
