### PR TITLE
Update developer install doc - issue #1440 :memo:

### PR DESCRIPTION
**Pull request by sebastien-lenard**
Update the developer install documentation to make sure that the creation of the environment takes into account all dependencies in the same call. This solves the issue #1440.

@mdpiper

### CODE REVIEW

**Comment by mcflugen** [comment]
Thanks @sebastien-lenard! 🎉

Before merging this, I would like to figure out what exactly is going on here. It doesn't make sense to me that it should make a difference if the dependencies are installed in one step or multiple steps.

**Comment by sebastien-lenard** [comment]
> 
Hi!
- I tried to launch the "pytest test_notebooks.py" on my dev environment (on the jupyter hub), it skips all notebooks. How is the pytest launched in the validation process?
- I checked the notebook run_network_generator_OpenTopoDEM.ipynb and it doesn't seem to have a dependency with the doc file of this pull.

**Comment by mdpiper** [comment]
@mcflugen When working with external code (C, Fortran), I've reliably encountered problems when creating a conda environment in a single step versus adding packages over multiple steps.

**Comment by mcflugen** [comment]
@sebastien-lenard The failure in that notebook is related to #1447 and has nothing to do with your this request.

**Comment by mcflugen** [comment]
> @mcflugen When working with external code (C, Fortran), I've reliably encountered problems when creating a conda environment in a single step versus adding packages over multiple steps.

@mdpiper Do you know why this might be? This also complicates things. You're saying you see problems when installing things in a single step, which is what this pull request is suggesting users do.

Maybe we should suggest users use *mamba* instead of *conda*. I wonder if this is a bug in how *conda* resolves dependencies.

**Comment by mdpiper** [comment]
@mcflugen Oh, I'm sorry, my wording was atrocious! I'll go back and edit the comment.

**Comment by mdpiper** [comment]
@mcflugen I guess it's conda's dependency resolution process. It solves an environment for one set of requirements, but then encounters conflicts when attempting to update the environment with an additional set of requirements.

**Comment by sebastien-lenard** [comment]
Hi, I'm still new to github, and just realized that I couldn't have two simultaneous pull requests. 

The new commit and pull "FramedVoronoiGrid creation issue #1450" is fully independent from:

"Update developer install doc - issue #1440".

I hope that it's not a problem that they are in the same pull request.

**Comment by mcflugen** [comment]
@sebastien-lenard Having them both in the same pull request is a problem—but a fixable one.

There should be no limit to the number of pull requests you can have at one time. What was the error you were seeing that prevented you from generating a second pull request?

**Comment by mcflugen** [comment]
@sebastien-lenard I think I see the problem.

When developing with *landlab* you should always create a new topic branch for each change/addition you are working on. For example, you could have created two new branches named something like, `update-installation-docs`, and `add-framed-voronoi-grid` and then worked on each of those branches separately and created separate pull requests .You've, instead, been working only on the *master* branch.

**Comment by sebastien-lenard** [comment]
Hi,
yes, I understood that afterwards. The new pull request button was simply deactivated in my case.

I had not made new modifications since my last commit. I think I managed to revert the commit and push by doing this locally:

```
git reset HEAD^
git push -f
```

**Comment by sebastien-lenard** [comment]
This pull request is replaced by #1452 which has been pulled on a dedicated branch.

**Pull request closed without merging**
