### PR TITLE
Barnhark/fix broken docs

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR addresses Issue #734 

Summary of things this does:
- removes numpydoc
- uses napoleon instead of numpydoc in building docs
- fixes two bits of the `build_grid_func_docs.py` file that had python 2/3 string/byte issues.
- turns building docs back on in travis

On my computer docs still don't build correctly and `make html` ends with this error. @mcflugen any ideas?

```
/Users/barnhark/projects/landlab/landlab/landlab/graph/object/at_node.py:docstring of landlab.graph.object.at_node.get_links_at_node:: WARNING: more than one target found for cross-reference 'Graph': landlab.graph.graph.Graph, landlab.graph.Graph

Exception occurred:
  File "/anaconda3/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 3543, in matches
    if s.identOrOp != identOrOp:
AttributeError: 'Symbol' object has no attribute 'identOrOp'
The full traceback has been saved in /var/folders/d_/zvv65dd52_g_k8xht41v676r0000gn/T/sphinx-err-hctxp_pm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen can you turn on building the docs on rtfd for this branch so we can test it fully and see what they would look like?

**Comment by mcflugen** [comment]
> can you turn on building the docs on rtfd for this branch so we can test it fully and see what they would look like?

I believe I've turned them on for this branch and it looks like they are building. Does building and viewing them locally not show the problem you're having? That's a pain.

**Comment by kbarnhart** [comment]
It appears to me that I have a local problem for building the docs BUT there is no problem when they are built in our Linux, python 3.6 build on Travis CI (the only build where we now test the docs...)

It looks like you turned it on, but it isn't working (https://readthedocs.org/projects/landlab/builds/7706749/)

Can you give me access to our read the docs backend?

**Comment by mcflugen** [comment]
@kbarnhart One thing that seems could be a problem is that `docs/sphinxext` is missing but the submodule is still listed in `.gitmodules`. Maybe you didn't properly remove the `sphinxext` submodule?

There's not a lot of information in the *readthedocs* logs for this build but, what does seem to be there, indicates RTFD might be having trouble with this submodule.

**Comment by kbarnhart** [comment]
Alrighty. This looks like it works. You can see the docs [here](https://landlab.readthedocs.io/en/barnhark-fix_broken_docs/)

I've done some spot checking and they look good to me. I have not pored through every page of the docs... I don't anticipate doing that. 

In order for this to totally take effect I think we will need to merge them _and_ make a release. That way all three versions of the docs on the website (`latest`, `release`, and `master`) will all be updated.

@mcflugen if we make a release for this, there are a few other things that I suspect should be in it (e.g. the results of PR #775, and maybe #780).

**Comment by kbarnhart** [comment]
@mcflugen @SiccarPoint OK to merge this?

**Comment by mcflugen** [comment]
> OK to merge this?

👍

**Comment by SiccarPoint** [comment]
Yup from me

**Pull request merged**
