### PR TITLE
Barnhark/improve read shapefile

### PR DESCRIPTION
**Pull request by kbarnhart**
Currently in progress, but eventually this will address @pfeiffea's #1138

### CODE REVIEW

**Comment by kbarnhart** [comment]
@pfeiffea I now have added all the capabilities we discussed over on #1138. It works on the example test case, but doesn't work on the example shape file you sent... I was looking at:

MethowSubBasin.shp and MethowSubBasin_Nodes_4.shp (correct?)

MethowSubBasin.shp has 29 links (so 30 nodes expected in MethowSubBasin_Nodes_4.shp). 
But MethowSubBasin_Nodes_4 had 59 points. I tried to delete obvious duplicates... and failed.

**Comment by pfeiffea** [comment]
Hi @kbarnhart I just made the fix to the nodes shapefile (very odd... I wonder how Jon was processing those in his Matlab version...) and pushed the changes. That should fix the issue.

**Comment by kbarnhart** [comment]
@pfeiffea I've now completed this. I added a few other things that I thought would be very useful. Specifically:

1) A way to indicate that only a subset of shape file attributes (for both node and link shape files) are imported as fields. 
2) A way to change the name of the shape file attributes to a new name on import. 
3) A way to indicate that you really want a shape file attribute being imported to have a specific data type. 

Hopefully you think these things are useful! 

Once this passes, I'll ask @mcflugen  to review.

**Comment by pfeiffea** [comment]
amazing @kbarnhart, this looks perfect.

**Comment by kbarnhart** [comment]
@pfeiffea glad you think so. 

As I was writing the tests, those were the three features that I felt would be useful in actually using this for application.

**Comment by kbarnhart** [comment]
@mcflugen any chance you can look at this?

**Comment by kbarnhart** [comment]
@mcflugen a quick ping to see if you have a moment to look at this. If there are more pressing things, do them

**Pull request merged**
