### PR TITLE
List all extensions in setup.py

### PR DESCRIPTION
**Pull request by mcflugen**
### Description

This pull request adds a list of all the extensions to be built to ``setup.py``. The downside of doing this is that this list must be manually updated when adding/removing extension modules but the upside is that it is more explicit and prevents unwanted extensions being found as in #1909.

### Checklist - did you ...

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by mcflugen** [comment]
@sebastien-lenard would you please have a quick look at this and let me know what you think?

A couple things:
1. All of *Landlab*'s extensions are now listed in ``setup.py``. Although maybe a bit more difficult to maintain, I think it's easier to understand and prevents extensions being built that shouldn't be built (as was the case in #1909).
2. There is an extension in the tests folder (``test_breach_c.pyx``), which looks to be yours, that I'm not sure about. I don't see why these tests need to be written as *cython*. It seems like they could more simply be written as Python and test the *priority_flow_routing* module directly.

**Review by sebastien-lenard — DISMISSED** [review]
Tested and worked on Jupyter hub.

**Comment by sebastien-lenard** [comment]
Hi @mcflugen !

_All of Landlab's extensions are now listed in setup.py. Although maybe a bit more difficult to maintain, I think it's easier to understand and prevents extensions being built that shouldn't be built (as was the case in https://github.com/landlab/landlab/issues/1909)._
Yes. 

_There is an extension in the tests folder (test_breach_c.pyx), which looks to be yours, that I'm not sure about. I don't see why these tests need to be written as cython. It seems like they could more simply be written as Python and test the priority_flow_routing module directly._
I can't directly call from a python script fully cythonized functions (),  in particular the ones having a nogil attributes (if I remember well), I need to pass through this intermediary cython script.

**Comment by mcflugen** [comment]
> I can't directly call from a python script fully cythonized functions (), in particular the ones having a nogil attributes (if I remember well), I need to pass through this intermediary cython script.

Thanks for that context. I think we can probably simplify this so that we can test those functions without having to compile additional cython code. If so, we'll do that in a separate pull request.

**Pull request merged**
