### PR TITLE
Add value-name decorator

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds a decorator that wraps a function so that it can accept either an array of a field name. This addresses #105.

The `use_field_name_or_array` decorator wraps functions whose first two arguments are a grid and an array. The first two arguments of the wrapped function become a grid followed by either a field name as a string or an array. If needed, the array is converted to a numpy array and then flattened.

Note that this does not change the docstring to reflect the change, but it should.

### CODE REVIEW

**Comment by SiccarPoint** [comment]
This is great, Eric. Thanks!

**Comment by mcflugen** [comment]
Thanks, Dan. Sorry it took so long. Since this was your idea, I'm going to assign you to review this. It's just about ready to be merged - but not quite. I'll let you know.

**Comment by SiccarPoint** [comment]
Sounds good. I’ll try to hit the docstrings too, if you haven’t got there.

D

**Comment by mcflugen** [comment]
Thanks. I think the docstring issue should probably be another pull request. What I'm thinking is that the new decorator should update the docstring of the function it's wrapping to reflect that the values can now be either an array or a field name.

**Comment by SiccarPoint** [comment]
That would indeed be cool - though manually reading for sense will probably still be needed, I guess.

**Comment by mcflugen** [comment]
@SiccarPoint, I think this is ready to go. If you could have a look before merging, that would be great. Thanks! If we like how this works, we could decorate many more functions but right now I've only applied it to the `calculate_gradients_*` functions for raster grids.

**Comment by SiccarPoint** [comment]
I’ll get to it on Monday!

D

**Comment by SiccarPoint** [comment]
This looks great to me. I guess it falls on later users to incorporate this on other functions.

Only immediate action item is to add a little documentation *somewhere* in the web docs about this, or it will end up being yet more functionality we have but nobody knows about.

A potential future action item will be an enhanced version of this where the field doesn't have to be the second param. i.e., a syntax like:

def myfunc(mg, nodevals, linkvals, **kwds):
    """
    This is the func to get wrapped.
    """"

def wrapper(object):
    def __init__(self, param-element-dict):
        """
        Here, param-element-dict is passed as:
        param-element-dict = {nodevals: 'node', linkvals: 'link'}
        """
        ...

**Comment by mcflugen** [comment]
Thanks!

If you're alright with this, I'll add this decorator to the rest of our functions that follow this pattern.

I don't think it would be too hard to add a keyword argument to this decorator that would give the name of the *field* argument. This would take care of cases where the field isn't the second param.
```python
@use_field_name_or_array('node', arg='node_values')
def my_func(grid, arg0, arg1, node_values):
    ...
```
I'll have a look at this tonight and, if it really isn't too hard, add it.

Where do you think we should add documentation for this in the web docs?

**Comment by SiccarPoint** [comment]
What about cases where there might be more than one field? Would that work too? Two decorators??

Re docs, I’m not totally sure. Maybe where we talk about fields:
http://landlab.readthedocs.org/en/latest/model_grid_no_tutorials.html#adding-data-to-a-landlab-grid-element-using-fields <http://landlab.readthedocs.org/en/latest/model_grid_no_tutorials.html#adding-data-to-a-landlab-grid-element-using-fields>

Maybe a sentence somewhere in there.

D

**Comment by SiccarPoint** [comment]
I'm merging this, on the assumption @mcflugen has in mind the need to update the docs...

**Pull request merged**
