### PR TITLE
Addresses DrainageDensity error

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR addresses the issues in DrainageDensity outlined in #842.

Importantly, it now requires that the channel mask is a uint8 dtype

It also
- makes the component fully tested
- expands the documentation
- changes the node processing order in the cython

I'm requesting @mcflugen to review. 

@jdgemperline please check this branch out and verify that it solves the problem you presented in Issue #842.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@jdgemperline a thing that you can do that would be really helpful

We have a new test to make sure DrainageDensity doesn't have the behavior you reported in #842 .

At its core is running the following model
```python
mg = RasterModelGrid((80, 80), 1.0)
_ = mg.add_zeros('node', 'topographic__elevation')
np.random.seed(50)
noise = np.random.rand(mg.size('node'))
mg.at_node['topographic__elevation'] += noise
mg.at_node['topographic__elevation'] # doctest: +NORMALIZE_WHITESPACE
fr = FlowAccumulator(mg, flow_director='D8')
fsc = FastscapeEroder(mg, K_sp=.01, m_sp=.5, n_sp=1)
for x in range(100):
    fr.run_one_step()
    fsc.run_one_step(dt = 10.0)
    mg.at_node['topographic__elevation'][mg.core_nodes] += .01
```

It would be ideal if the grid size (currently 80x80) and the number of time steps (100) were as small as possible (while still resulting in the error).

Can you please play around with different grid sizes, numbers of time steps (and possibly random seeds) to identify the smallest possible grid and time step size we can use to reproduce this error

**Comment by kbarnhart** [comment]
Also. I've turned on building these docs so we can see how they look (and to make improvements, and check math formatting) . 

https://landlab.readthedocs.io/en/barnhark-fix_drainage_density_bug/landlab.components.drainage_density.html

**Comment by jdgemperline** [comment]
Just to clarify, the test should check and see if channel nodes are changed only if they're not along an open boundary, correct?

**Comment by kbarnhart** [comment]
@jdgemperline you should use the current version of landlab `master` (that is, not this branch). And you should try and find the smallest grid (and number of time steps) for which some of the nodes ID'd as channel in your original mask are then set from 1 (channel) to 0 (not channel). Does that make sense?

**Comment by jdgemperline** [comment]
Got it! Here's the whole MWE that I used to replicate the issue. I tweaked the grid size, K for the fastscape eroder, time steps, and identifying channels. I didn't get any grids smaller than 10x10 to replicate the issue, though it may be possible if you want to try and make the test even quicker.


'''
import numpy as np
from landlab import RasterModelGrid
from landlab.components.flow_routing import FlowRouter
from landlab.components import FastscapeEroder, DrainageDensity
from landlab.plot import imshow_grid
import matplotlib.pyplot as plt, numpy as np

size = 10 # Changes grid size and length of noise array
mg = RasterModelGrid((size, size), 1.0) #instantiate a grid
_ = mg.add_zeros('node', 'topographic__elevation')
np.random.seed(3542) # This is the random seed I used to replicate the problem I was having
noise = np.random.rand(size*size)
mg.at_node['topographic__elevation'] += noise #add noise to grid
mg.at_node['topographic__elevation'] # doctest: +NORMALIZE_WHITESPACE
fr = FlowRouter(mg) # Old example used FlowRouter, should work fine with the accumulator
fsc = FastscapeEroder(mg, K_sp=.5, m_sp=.5, n_sp=1) #tweaked K
for x in range(2):
    fr.run_one_step()
    fsc.run_one_step(dt = 10)
    mg.at_node['topographic__elevation'][mg.core_nodes] += .5 # add uplift after timesteps

mask = np.zeros(len(mg.at_node['topographic__elevation'])) # create a mask for drainage density
mask[np.where(mg.at_node['drainage_area'] > 0)] = 1 # setting all nodes as channels makes it more likely the problem appears

#%matplotlib inline
#imshow_grid(mg, mask)
#plt.show()

dd = DrainageDensity(mg, channel__mask=mask)

#imshow_grid(mg, mask)
#plt.show()

mean_drainage_density = dd.calc_drainage_density() #One node towards the bottom left should be altered after
# running this line of code

#imshow_grid(mg, mask)
#plt.show()
'''

**Comment by kbarnhart** [comment]
thanks @jdgemperline !

**Pull request merged**
