### PR TITLE
Tidy up CI on Travis

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request mainly cleans up the landlab CI on Travis. In doing so, it may also address some issues raised #910, and #911 (i.e. ensuring when we build with Python 3.7, we really build with 3.7 and not downgrade to 3.6).

Some highlights:
* Break up the build on Travis into stages: test, lint, docs, deploy (to PyPI)
* Add requirements to *setup.py* to make landlab pip-installable
* For testing, install Python with conda but install landlab with pip. We hadn't been testing pip installs before. Our conda installs will still be tested with conda-forge
* On success, deploy to PyPI. We had only been doing this on Windows. Somewhere along the way we stopped deploying to PyPI from Travis

I still need to clean up the requirements files. I think `requirements.txt` maybe should have packages not strictly needed by landlab (i.e. those in setup.py) but packages required for developers (*pytest*, *flake8*, etc.). There should also be a conda environment file for landlab developers that want to use conda as a package manager instead of pip.

### CODE REVIEW

**Comment by kbarnhart** [comment]
🎉

**Comment by kbarnhart** [comment]
@mcflugen a couple of things:

As we discussed earlier today, this PR should get rid of the Win32  bit builds. 
- [ ] Remove Win32 bit builds from AppVeyor

It also doesn't seem to fix the #911 issue. Instead it extends `setup.py`  to add additional requirements, adds an `environment.yaml` and doesn't add any of the things  @SiccarPoint wanted to add to the `requirements.txt` file (e.g. pytest, pytest-cov, flake8). 

I don't have a problem with adding an `environment.yaml` file, but I think the following should be done:

- [ ] All the conda build related stuff should get removed in this PR. It should only live in the Conda-forge repo  where we build that recipe.
- [ ] Both `environment.yaml` and `requirements.txt` should include EVERYTHING necessary for a developer to build, test, evaluate lint, and calculate coverage.

@SiccarPoint do  you have any additional comments.

**Comment by kbarnhart** [comment]
@mcflugen this looks great to me! 

My only question is: Do you think it makes sense to get rid of the `requirements.txt` file? 

My vote is yes. In an `environment.yaml` we are providing the minimally sufficient conditions to run/test/dev landlab. If someone wants to run landlab/master outside of this conda environment, they have a list of all the packages they need. By providing the requirements in ONLY `environment.yaml` we are making it (a) super easy to create a functional conda environment and (b) putting the requirements only in one spot. 

As it stands, this PR would need to be accompanied by:
 - [ ] changes to the wiki developer install instructions (including how to tell if the conda env needs to be updated...) (check box sorta silly as these changes only should occur after merge to master).

Perhaps other landlabbers (@gregtucker @SiccarPoint @saisiddu @nicgaspar @nathanlyons @erkanistan) want to weigh in on changes to `requirements.txt` as well.

**Comment by mcflugen** [comment]
@kbarnhart I removed the Windows 32 builds and cleaned up the build process on AppVeyor in the process. It now uses *pip* to build landlab, which meant that I was able to remove the conda build stuff, as you suggested. Unfortunately, *netcdf4* seems to not be *pip* installable on Windows so I have to install it with conda for the AppVeyor builds.

I added a *environment-dev.yml* file for a complete installation environment for developing with landlab. I removed *requirements.txt* to avoid repeating the requirements, which are also in *environment-dev.yml* and also in *setup.py*. I added a new requirements file with just the extras needed to develop with landlab (*pytest*, *black*, etc.). Since the install requirements for landlab are now in *setup.py*, I didn't think we also needed them in *requirements.txt*.

To install a development version of landlab you could do one of the following,
```bash
$ pip install -e . -r requirements-dev.txt
```
or
```bash
$ conda env create --file=environment-dev.yml
```

**Comment by kbarnhart** [comment]
@mcflugen 🎉 I think this looks great! I really like how its been cleaned up and the splitting of requirements between `setup.py` and `requirements-dev.txt`. It makes a lot of sense to me and seems much cleaner. 

Am I crazy to think that the following is what is needed to do a full conda install?

```bash
$ conda env create --file=environment-dev.yml
$ conda activate landlab_dev
$ python setup.py develop
```

I also just looked through the Travis builds and I noticed that the coveralls command doesn't seem to be working. 
- [ ] fix coveralls command

**Comment by kbarnhart** [comment]
Looks like the coveralls issue is fixed. For example: https://coveralls.io/jobs/47945505

**Comment by kbarnhart** [comment]
@mcflugen Should I make a new issue and assign you related to updating the install and update instructions on the wiki?
Or is mentioning it here sufficient?

**Pull request merged**
