### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request fixes most of the warning issued when the landlab tests are run. There were just over 21k warnings, which was both annoying and made it difficult to look at the testing output. I've fixed most of them and there are now just over 120. Most of the remaining ones lie in various components and are mostly (but not all) divide-by-zero warnings. Eventually these warnings should probably also be addressed but is a job for the component authors.

In case any component authors would like to address this in this pull request, the components are:
- [ ] species_evolution
- [ ] chi_index
- [ ] lithology
- [ ] materiallayer
- [ ] data_record
- [ ] grain_hill
- [ ] depth_dependent_taylor_soil_creep
- [ ] drainage_density
- [ ] groundwater
- [ ] lateral_erosion
- [ ] overland_flow
- [ ] stream_power
- [ ] taylor_nonlinear_hillslope_flux

I don't think it's necessary that all these be fixed, as things have seemingly be working just fine, but it's possible the warnings point to real issues.

I'm not sure who these bits of code belong to but maybe @nathanlyons, @DavidLitwin, @kbarnhart?

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen I love it. Once this passes I'll merge into master, and then finalize #1187. Sound good?

**Comment by gregtucker** [comment]
@mcflugen bravo! I'll take a look at warnings related to GrainHill and some of the others.

**Comment by kbarnhart** [comment]
@gregtucker this is great! Might you address any remaining warnings on a different PR? I'm waiting for the CI on this PR to pass, so I can merge it into master, and then finalize the 2.0 release over on #1187. The CI presently takes about 3 hours to complete.

**Comment by DavidLitwin** [comment]
@mcflugen I know exactly where the divide by zero error occurs in the groundwater code. It doesn't cause any unintended behavior but it is a little annoying. I can try to find a solution sometime soon, but probably not right now.

**Comment by mcflugen** [comment]
@kbarnhart Thanks. I didn't intend for this to be a last minute addition to our 2.0 release but if you think you can fit it in, that would be great. Otherwise, it can find its way into v2.0.1.

@gregtucker Thanks!

@DavidLitwin No problem at all if you can't get to this today. At least it's on your radar.

**Comment by kbarnhart** [comment]
Awesome @DavidLitwin! 

@mcflugen glad to know. reducing warnings by that quantity seems like something to get into the release... it should still be able to happen later today.

**Comment by kbarnhart** [comment]
@mcflugen since this has some lint issues I'm going to move forward with the 2.0 release without it. As you mentioned, it doesn't _need_ to be in it.

**Comment by gregtucker** [comment]
I'll hold any further warning fixes for another PR. In the meantime, BRAVO FOR MRS. WEASLEY!

**Comment by kbarnhart** [comment]
@gregtucker - apologies. I thought this was going to be able to get into 2.0, but that was not the case. 🤦 

As @mcflugen said, it can be part of v2.0.1.

**Pull request merged**
