### PR TITLE
SiccarPoint/fix issue 250

### PR DESCRIPTION
**Pull request by SiccarPoint**
Addresses issue #250 .

### CODE REVIEW

**Comment by SiccarPoint** [comment]
Should all be fine, nothing very controversial here. Hit a surprisingly large number of doctests though:  if you show field creation twice in one docstring, you'll now by default get an exception unless you modify the flag. I fixed them all though, and still think this is the right behavior for the user.

**Comment by SiccarPoint** [comment]
Bump @mcflugen : This guy wants merging. I just rebased off Master, so the previously failing tests (unrelated to these changes) hopefully will now pass.

**Comment by SiccarPoint** [comment]
Found a bug where only the add_field method responded at all to the noclobber default (i.e., not add_zeros, _ones, _empty). Kicked off a bunch more unit test fails. Should all now pass.

I've reassigned this to @jadams15, as the only tests that I hit that weren't my own were yours when I mended this bug - in deAlmeida. I resolved the issue by modifying the component itself to ingest existing fields where it finds them and overwrite them with zeros. (Just setting noclobber=False in the component wouldn't be a good option, as it would break references in any other components using the existing field). This basically exactly replicates the old behaviour.

However, a better option might be to restore the original form of the component (so errors get raised if output fields already exist, if they aren't also input fields), then modify the tests themselves to not create these fields before instantiation. This is how I have my components set up mostly, as generally you want to know about it if a field your component is trying to write to already exists...

**Comment by mcflugen** [comment]
I added some tests for the `noclobber` keyword.

It made me wonder. Since `noclobber` is the default, would it make more sense to have the keyword be, instead, `clobber`?

```python
>>> grid.add_ones('z', at='node', clobber=True)
```
vs.
```python
>>> grid.add_ones('z', at='node', noclobber=False)
```
`noclobber=False` seems unnecessarily confusing and a double-negative.

Thoughts?

**Comment by SiccarPoint** [comment]
Is there a numpy standard or commonly used argument for allowing overwrite? We should probably adopt that… Given you adopted `noclobber` back in the mists of time, Eric, I’ll defer to your opinion! Don’t feel strongly at all if there isn’t something numpy uses.

**Comment by mcflugen** [comment]
OK. Thanks. Originally, the default was to clobber an existing field so, to suppress this behavior, one would use `noclobber=True`, which made a little more sense. In any case, I think I would like to change the keyword to `clobber`. I will look for precedent in numpy/scipy, though, and any changes will be done in another branch and another pull request.

**Comment by SiccarPoint** [comment]
Sounds like a plan!

**Comment by SiccarPoint** [comment]
I've been fine with it. The order is the same as any of our field interfaces in my brain - grid-then-node-then-name. E.g., mg.at_node['field']. And it's pretty well ingrained throughout the code because the docs have said to do it this way.

If you do change it, make sure to do a thorough job everywhere- tests, components, examples, wiki, tutorials... The lot. But perhaps consider if this would come under change for change's sake before committing to it. And let's make it a new issue, for sure.

**Comment by mcflugen** [comment]
Oh yeah. This would be in a different branch, for sure.

**Comment by nicgaspar** [comment]
@SiccarPoint @mcflugen 

In a teaching tutorial I'm having a `noclobber` problem. The code block and error are attached. I sometimes need to instantiate the `SteepnessFinder` more than once, because I might vary parameters that affect `reference_concavity`. But then I have a `no_clobber` problem because the field `channel__steepness_index` already exists. I thought maybe if I created that field first and set `noclobber` to False, then I might get around the problem, but that doesn't work. I guess there is a simple solution that I'm not seeing. Can you help?
screen shot 2018-05-21 at 2 00 32 pm

**Comment by mcflugen** [comment]
@nicgaspar The easy fix is to recreate your grid. The field is attached to the grid, not the component, so re-instantiating the `SteepnessFinder` doesn't help. Would that work for you example?

The slightly more difficult solution is to modify the `SteepnesssFinder` component to deal with this case. The user could control what happens if the field already exists:
* Do nothing. Use the existing field as-is
* Initialize the field
* Raise an error (the current behavior)

**Comment by SiccarPoint** [comment]
Easier way: Looks like I designed this with this use case in mind. You should find a single instantiation works, then you can pass `reference_concavity` direct to `calculate_steepnesses` as a `**kwd`; see the documentation on that function. i.e., you can override the initiation variables at any time in this component.

**Comment by nicgaspar** [comment]
Thanks @SiccarPoint. That is way easier. For whatever reason it didn't occur to me to check that option.

**Pull request merged**
