### PR TITLE
Gt more cts cython

### PR DESCRIPTION
**Pull request by gregtucker**
This PR adds a bit more cythonizing to CellLab. It is still quite slow for some cases. From profiling, the bottleneck seems to be the do_transition() and update_link_states() functions. @mcflugen could you take a quick look?

### CODE REVIEW

**Comment by gregtucker** [comment]
Ok, I think I've gotten about as far as I can with this.

**Comment by mcflugen** [comment]
@gregtucker, I'm at the airport right now but will have a look at this as soon as I can and then merge. Do you want me to look into trying to speed it up or just a quick review and merge?

**Comment by SiccarPoint** [comment]
Please don't merge this til after #377 ! I've already been through that sucker 4 times dealing with the same set of conflicts after every merge. It appears to just not be tracking changes right, as most of them aren't conflicts.

**Comment by gregtucker** [comment]
@mcflugen , if you spot any places to speed it up, please let me know! (or even better, go for it!). If there are no obvious further bottlenecks, then just a review and merge. I'm basically stuck with the need to pass a python object: the event_queue (i.e., the heap that contains transition events). _heapq is implemented in C but it uses a python list object.

**Comment by gregtucker** [comment]
Actually, let's hold off on merging this for a bit, I have an idea to test...

**Comment by gregtucker** [comment]
This should be ready to review and merge once the tests finish (took a while to sort out the python 3 import issues, since I'm running python 2).

**Comment by gregtucker** [comment]
I'm going to merge this CTS cython PR, as I need it for the next steps...

**Comment by kbarnhart** [comment]
I merged master into my present branch after you made this commit and am now getting test errors. 

10 errors all appear to be the same:

```
File "/Users/katybarnhart/git/landlab/landlab/ca/celllab_cts.py", line 142, in <module>
    from .cfuncs import PriorityQueue
ImportError: cannot import name 'PriorityQueue'
```

**Comment by gregtucker** [comment]
Try running
python setup.py develop
In main landlab repo folder

Sent from my iPhone

On Dec 29, 2016, at 11:07 AM, Katy Barnhart <notifications@github.com<mailto:notifications@github.com>> wrote:


I merged master into my present branch after you made this commit and am now getting test errors.

10 errors all appear to be the same:

File "/Users/katybarnhart/git/landlab/landlab/ca/celllab_cts.py", line 142, in <module>
    from .cfuncs import PriorityQueue
ImportError: cannot import name 'PriorityQueue'


-

**Comment by kbarnhart** [comment]
Worked! That's right. New things in .cfuncs require re-running python setup.py develop.
Thanks!

**Pull request merged**
