### PR TITLE
Touch documentation

### LINKED ISSUE #1289: Include docs requirements in dev environment
This is a request to add `requirements-docs.txt` to `environment-dev.yml`.

While using the dev environment to work with the LL source, I wanted to update corresponding documentation. I was surprised when the docs didn't build because sphinx wasn't installed in the environment.

### PR DESCRIPTION
**Pull request by mdpiper**
This PR is a collection of minor adjustments ("updates" is too strong a word) to the LL documentation, including modifications to:

- the LL 2.0 comment
- Python version support
- the list of clinics and workshops
- the LL v1 and v2 references

This PR also fixes #1289.

### CODE REVIEW

**Comment by mdpiper** [comment]
I note that the `black` check failed. It would be easy to fix the problems, but it's outside the scope of this PR. Should I just fix this anyway?

**Comment by gregtucker** [comment]
👍

**Comment by mcflugen** [comment]
@mdpiper Please go ahead and fix the formatting. It surprises me this had made it through. I wonder if it is a minor change to *black*.

**Comment by mdpiper** [comment]
@mcflugen My hunch is you're right--it's a change to *black*.

**Review by mcflugen — APPROVED** [review]
👍

**Pull request merged**
