### PR TITLE
Fix links_at_patch bug

### PR DESCRIPTION
**Pull request by mcflugen**
### Description

This pull request fixes a bug when ordering one element around another (e.g. ordering *links* in counterclockwise order around a patch).

The function ``sort_links_at_patch`` (defined in ``landlab/graph/sort/sort.py``) should now correctly sort the links that form a patch so that links are listed in counterclockwise order. Its *docstring* should demonstrate this.

@ethan-pierce Could you please have a look at this?

### Checklist - did you ...

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by ethan-pierce** [comment]
I'm getting a ModuleNotFound error for landlab.graph.quantity.ext.of_element. Should there be an of_element.py in the same dir as of_link.py and of_patch.py ?

**Comment by mcflugen** [comment]
> I'm getting a ModuleNotFound error for landlab.graph.quantity.ext.of_element

``ext/of_element.pyx`` is a new extension module so you have to compile it by reinstalling landlab (``pip install -e .``). That should do it.

**Comment by ethan-pierce** [comment]
Right, right, so everything looks good with the links_at_patch, and I checked that the methods that were breaking with it previously are working now. I'm still getting zero length for some faces, but beginning to suspect that is related to a different bug.

**Comment by mcflugen** [comment]
> I checked that the methods that were breaking with it previously are working now.

🎉 

>  I'm still getting zero length for some faces

Bummer. Keep me updated.

**Review by ethan-pierce — APPROVED** [review]

**Pull request merged**
