### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by kbarnhart**
Addresses Issue #798

### CODE REVIEW

**Comment by kbarnhart** [comment]
I've also updated the wiki

https://github.com/landlab/landlab/wiki/Installing-Landlab-from-source-code-(%22developer-install%22)#testing-your-install

**Comment by mcflugen** [comment]
Looks good to me. Thanks, @kbarnhart!

**Comment by SiccarPoint** [comment]
Looks good. I tweaked the wiki slightly further to make it clearer how to run the coverage tests on only a local part of the code.

**Comment by SiccarPoint** [comment]
So, this PR resolves #796, and I'm merging.

**Pull request merged**
