### PR TITLE
Treatment of porosity in E/d and SPACE fixed

### PR DESCRIPTION
**Pull request by cmshobe**
This PR addresses an error with how SPACE and E/D treated porosity. Specifically, I took porosity out of the Qs_in cfuncs calculation and added it into the appropriate places in the erosion terms of each component's sediment depth solver.

One note: At steady state, SPACE will always be insensitive to sediment porosity because only rock is being exhumed at the imposed uplift rate. This is true except for the "infinite sediment depth" case in which the model reaches the transport-ltd end-member and is in fact incising only through sediment.

This PR also includes new default values for SPACE and ED, addressing #938. The "generalized ED" function (under the hood functionality for SPACE and ED) now takes positional arguments instead of keyword arguments.

@kbarnhart

### CODE REVIEW

**Comment by kbarnhart** [comment]
@cmshobe thanks for doing this (and for making the Issue over in the terrainbento repo). Could you please add at least one test that demonstrates that using different phi results in a different transient solution. Clearly it can't be as steady state solution, and I don't expect it will be analytically-based. But something would be good. 

There are also a very small number of additional lines that could benefit from a test. They should be trivial to do (and you can see exactly which lines on coveralls, links below). Some of them should be very easy fixes requiring no actual tests replacing an if with a different approach. 

For example, the only change needed in space is:
```python
dt_max = min(dt_max1, dt_max2)
if dt_max < self.dt_min:
    dt_max = self.dt_min
```
becomes
```python
ddt_max = np.min(self.dt_min, dt_max1, dt_max2)
```

Coveralls Links
* [generalized](https://coveralls.io/builds/24118320/source?filename=landlab/components/erosion_deposition/generalized_erosion_deposition.py)
* [erosiondeposition](https://coveralls.io/builds/24118320/source?filename=landlab/components/erosion_deposition/erosion_deposition.py)
* [space](https://coveralls.io/builds/24118320/source?filename=landlab/components/space/space.py)

**Comment by cmshobe** [comment]
@kbarnhart I will add a test showing that changing phi changes the transient behavior. I'll note though just for the record that phi is already tested in the TL steady solution, because that particular solution is sensitive to phi

**Comment by kbarnhart** [comment]
@cmshobe if you want to check the coverage locally (and not do it for the entire module) try:

```bash
>>> TEST_DIR=landlab/components/erosion_deposition/
>>> pytest $TEST_DIR --doctest-modules --cov=$TEST_DIR --cov-report term-missing
```

You don't have to do the $TEST_DIR thing if you don't want, I just prefer not to type the path twice. 
The example assume you are in the top level directory of LL

If you haven't updated your environment in a while, you may find that you don't have pytest or coveralls.

**Comment by cmshobe** [comment]
@kbarnhart the Travis builds are timing out... All I've changed in here are those timestep minimum statements. Can you have a lok and see if you can understand the problem?

**Comment by cmshobe** [comment]
Ok I think I found it... Those timestep comparison statements need to be np.maximum() not minimum, because youre setting dt_max to self.dt_min if it would have been smaller.

**Comment by cmshobe** [comment]
Everything looks fixed no. Still TODO:

- get lines in E/D adaptive solution covered
- add transient behavior test for phi to E/D and SPACE

**Comment by cmshobe** [comment]
@kbarnhart this is basically done except that there is a problem with the dynamic timestepper (unrelated to the phi thing). A few notes:

- None of the tests really tested the dynamic timestepper, because they all used a small enough dt that subdivision wasnt needed. 

- When I finally made a test that actually tested the dynamic timestepper, the test failed and continues to do so whenever the dt is large enough to require subdivision. 

- I am not familiar enough with the dynamic timestepper to understand why this is

I'm going to leave this aside until someone more familiar with the dynamic timestepper takes a look; we can't get to full coverage until that solver is working.

**Comment by kbarnhart** [comment]
@cmshobe thanks for getting this PR to this point. @gregtucker is the person with the knowledge of the dynamic time stepper.

**Comment by cmshobe** [comment]
Could I please request that the changes up through commit e30dafd be merged so that the code people are using is correct?

The adaptive thing can come later

**Comment by cmshobe** [comment]
Ok, I've rolled it back so we're at the point where all the porosity stuff is fixed. We should merge to get those changes in, then deal with the adaptive thing later. I'll be out of this until I'm all defended...

**Comment by kbarnhart** [comment]
@mcflugen I think we have a py27 CI issue that this PR raises. I'm a bit surprised that the error includes Scipy 1.3, though, since the `setup.py` file indicates <1.3

Any thoughts on a quick fix? 

```
Executing: pip install -e .
354Obtaining file:///C:/projects/landlab
355Collecting bmipy<1 (from landlab==1.9.0b4+34.g67212bf4)
356  Downloading https://files.pythonhosted.org/packages/f5/c8/b7f33ad23a89ce0632c45bfdd1fc64928f300ef5bbf826eb29389887a2d4/bmipy-0.3.2.tar.gz
357Collecting matplotlib (from landlab==1.9.0b4+34.g67212bf4)
358  Downloading https://files.pythonhosted.org/packages/21/93/759d9f5a6c4b5c1fb489bb57200fc2f553c524642bc2756ae2528dbed6b5/matplotlib-2.2.4-cp27-cp27m-win_amd64.whl (8.7MB)
359Requirement already satisfied: netcdf4 in c:\miniconda-x64\lib\site-packages (from landlab==1.9.0b4+34.g67212bf4) (1.4.2)
360Collecting pyyaml (from landlab==1.9.0b4+34.g67212bf4)
361  Downloading https://files.pythonhosted.org/packages/a2/fc/b1ead6200056e3c8b6a605249aa78445f728ceb9c19a51a148d43a4256da/PyYAML-5.1.1-cp27-cp27m-win_amd64.whl (210kB)
362Collecting pyshp (from landlab==1.9.0b4+34.g67212bf4)
363  Downloading https://files.pythonhosted.org/packages/27/16/3bf15aa864fb77845fab8007eda22c2bd67bd6c1fd13496df452c8c43621/pyshp-2.1.0.tar.gz (215kB)
364Collecting scipy<1.3 (from landlab==1.9.0b4+34.g67212bf4)
365  Downloading https://files.pythonhosted.org/packages/49/73/22e125f335986fdc3b03c09cdf8ffe0d9d5471eec301aeb2e33db78b3e7f/scipy-1.2.2-cp27-cp27m-win_amd64.whl (30.5MB)
366Requirement already satisfied: six in c:\miniconda-x64\lib\site-packages (from landlab==1.9.0b4+34.g67212bf4) (1.12.0)
367Collecting statsmodels (from landlab==1.9.0b4+34.g67212bf4)
368  Downloading https://files.pythonhosted.org/packages/ff/cd/d97aae2d2a96231288489eaeb08f91a62c48d83e345fb0ea777472fdb3d6/statsmodels-0.10.0.tar.gz (14.0MB)
369    Complete output from command python setup.py egg_info:
370    Traceback (most recent call last):
371      File "<string>", line 1, in <module>
372      File "c:\users\appveyor\appdata\local\temp\1\pip-install-5t5pl2\statsmodels\setup.py", line 346, in <module>
373        data_files=[('', ['LICENSE.txt', 'setup.cfg'])]
374      File "C:\Miniconda-x64\lib\site-packages\setuptools\__init__.py", line 142, in setup
375        _install_setup_requires(attrs)
376      File "C:\Miniconda-x64\lib\site-packages\setuptools\__init__.py", line 137, in _install_setup_requires
377        dist.fetch_build_eggs(dist.setup_requires)
378      File "C:\Miniconda-x64\lib\site-packages\setuptools\dist.py", line 586, in fetch_build_eggs
379        replace_conflicting=True,
380      File "C:\Miniconda-x64\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
381        replace_conflicting=replace_conflicting
382      File "C:\Miniconda-x64\lib\site-packages\pkg_resources\__init__.py", line 1063, in best_match
383        return self.obtain(req, installer)
384      File "C:\Miniconda-x64\lib\site-packages\pkg_resources\__init__.py", line 1075, in obtain
385        return installer(requirement)
386      File "C:\Miniconda-x64\lib\site-packages\setuptools\dist.py", line 653, in fetch_build_egg
387        return cmd.easy_install(req)
388      File "C:\Miniconda-x64\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
389        return self.install_item(spec, dist.location, tmpdir, deps)
390      File "C:\Miniconda-x64\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
391        dists = self.install_eggs(spec, download, tmpdir)
392      File "C:\Miniconda-x64\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
393        return self.build_and_install(setup_script, setup_base)
394      File "C:\Miniconda-x64\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
395        self.run_setup(setup_script, setup_base, args)
396      File "C:\Miniconda-x64\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
397        run_setup(setup_script, args)
398      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
399        raise
400      File "C:\Miniconda-x64\lib\contextlib.py", line 35, in __exit__
401        self.gen.throw(type, value, traceback)
402      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
403        yield
404      File "C:\Miniconda-x64\lib\contextlib.py", line 35, in __exit__
405        self.gen.throw(type, value, traceback)
406      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
407        saved_exc.resume()
408      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 141, in resume
409        six.reraise(type, exc, self._tb)
410      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
411        yield saved
412      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
413        yield
414      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
415        _execfile(setup_script, ns)
416      File "C:\Miniconda-x64\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
417        exec(code, globals, locals)
418      File "c:\users\appveyor\appdata\local\temp\1\easy_install-zsql4t\scipy-1.3.0\setup.py", line 31, in <module>
419        from distutils.command.clean import clean
420    RuntimeError: Python version >= 3.5 required.
421    
422    ----------------------------------------
423Command "python setup.py egg_info" failed with error code 1 in c:\users\appveyor\appdata\local\temp\1\pip-install-5t5pl2\statsmodels\
```

**Comment by kbarnhart** [comment]
@mcflugen did something change (here and elsewhere, for example on #945)? Looks like the Appveyor and Travis PR builds happened, but we are hung waiting for the Appveyor branch build, which doesn't exits.

**Pull request merged**
