### PR TITLE
Create pytest on the cython func of FlowDirectorSteepest #1459 

### PR DESCRIPTION
**Pull request by sebastien-lenard**
To address the possibility that unit tests also cover cython code #1459 point 2, this small delivery of a unit test file for the function def adjust_flow_receivers which underlies the FlowDirectorSteepest.run_one_step().

NB: Retry of pull request #1460 which was built with a commit initially for another pull request #1454

### CODE REVIEW

**Comment by sebastien-lenard** [comment]
Hi @mcflugen ! This request is ready for review, if you have time. Thanks!

**Comment by mcflugen** [comment]
@sebastien-lenard I made a couple tweaks, the main one was to move the test into a function. If the test isn't in a function, then it will get run when *pytest* is looking for tests rather than when it runs the tests.

Would you be able to rewrite the test without using random input data? Because you're using random input, it's not clear to me that the *adjust_flow_receivers* function is working correctly. A better test would be one where you know what the correct output should be before you run the test.

**Comment by sebastien-lenard** [comment]
> @sebastien-lenard I made a couple tweaks, the main one was to move the test into a function. If the test isn't in a function, then it will get run when _pytest_ is looking for tests rather than when it runs the tests.
> 
> Would you be able to rewrite the test without using random input data? Because you're using random input, it's not clear to me that the _adjust_flow_receivers_ function is working correctly. A better test would be one where you know what the correct output should be before you run the test.

Thank you @mcflugen.

The topography is actually not random since the seed is fixed to 500. Then, the random_generator.random(nodes_n)) always produce the same array. Would you still prefer I replace the syntax?

**Comment by mcflugen** [comment]
> Would you still prefer I replace the syntax?

I would. Even though the test is repeatable, it's not clear to me that *adjust_flow_receivers* is generating the correct output. I may be missing something but it appears that you created some random input, ran it through *adjust_flow_receivers*, and then copied that output into you test. Instead, I would like to see a test that uses input for which you know the output before running the tested function.

**Comment by sebastien-lenard** [comment]
@mcflugen I updated the test file, could you validate it? thanks :)

**Comment by mcflugen** [comment]
@sebastien-lenard I've add three more unit tests for *adjust_flow_receivers*: two for a dipping plane on a raster grid, and one for a dipping plane on a hex grid.

**Comment by sebastien-lenard** [comment]
Thank you @mcflugen, I tried your new version and it works. May you validate this request or does it remain something to do?

**Comment by sebastien-lenard** [comment]
Hi @mcflugen, May you validate this request or does it remain something to do?
Thank you!

**Comment by sebastien-lenard** [comment]
Hi @mcflugen! A new problem about coverage is now raised and seems unrelated to this request which files are tests:
```
Coveralls - false — Coverage decreased (-0.0%) to 85.934%
```
I'll perform the merge 9/2 except if you have any remarks.
Thanks!

**Comment by mcflugen** [comment]
@sebastien-lenard I've changed the threshold for the decrease in percent coverage (was 0.0%, now 0.1%) so, hopefully, we won't see this error again.

**Pull request merged**
