### PR TITLE
Fix readthedocs build

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request fixes the building of our docs on *readthedocs*. The error is described by @kbarnhart in a comment in #1169. I'm not totally sure what the problem was but I think it may have had something to do with *conda*, so I switched to *pip* to install the doc environment.

### CODE REVIEW

**Comment by mcflugen** [comment]
@nathanlyons, @kbarnhart Would one of you be kind enough to give this a review? Thanks!

**Comment by mcflugen** [comment]
Thanks for having a look at this @nathanlyons! Fingers crossed it still works on *master*. 🤞

**Comment by SiccarPoint** [comment]
The online pages are still unchanged for this. Will we have to update master for this to trigger?

**Comment by kbarnhart** [comment]
readthedocs looks updated on master to me. https://landlab.readthedocs.io/en/master/user_guide/tutorials.html

Its not updated on release yet (though the present default for rtfd is master right now)

**Comment by mcflugen** [comment]
@SiccarPoint Which pages are you referring to? This pull request was just to get he docs building again, I hadn't been targeting any specific pages.

What you see now on *readthedocs* should reflect what's on *master*.

**Comment by mcflugen** [comment]
@kbarnhart Yes, that's correct. Should we merge these changes into *release*? I guess it's not all that important if *master* is the default.

**Comment by kbarnhart** [comment]
@mcflugen I think a new release is a good idea (once whatever problem @SiccarPoint thinks exists is addressed).

**Comment by SiccarPoint** [comment]
It's not updated in the sense that this:

https://landlab.readthedocs.io/en/master/user_guide/tutorials.html

...isn't the same text as this:

https://github.com/landlab/landlab/blob/master/docs/source/user_guide/tutorials.rst

?

**Comment by mcflugen** [comment]
@SiccarPoint Maybe I'm missing something but they look the same to me. Perhaps your browser has cached the old page? Or maybe I'm missing something...

**Comment by kbarnhart** [comment]
I observe the same thing as @mcflugen.

**Comment by SiccarPoint** [comment]
Gotcha, browser must have cached it somehow. Forced reload gets me seeing what you are. Looks good!

**Pull request merged**
