### PR TITLE
the NetworkSedimentTransporter

### PR DESCRIPTION
**Pull request by pfeiffea**
@kbarnhart @mcflugen @jonczuba

New component, huzzah!

### CODE REVIEW

**Comment by kbarnhart** [comment]
🦖 🎉 @pfeiffea !

A brief summary for @mcflugen (who we hope will review this for bringing into Landlab in advance of submitting to JOSS).

Since this is a big PR, I'll summarize:

This PR adds a new component, the NetworkSedimentTransporter and a new plotting function to assist with plotting its output (`plot_network_and_parcels`). There are three notebooks that highlight use of the NetworkSedimentTransporter and plotting function (landlab/notebooks/tutorials/network_sediment_transporter). 

There are test for both the component and plotting function. 

I *think* I've added everything to the docs, and the welcome.ipynb notebook correctly...

The component submodule has a readme.md that has links that won't work yet (but once a release is made, it should work).

**Comment by kbarnhart** [comment]
Check this out @pfeiffea all the tests pass!

**Comment by mcflugen** [comment]
@pfeiffea Nice work! This is really great.

Do you need all of those data files (particularly the binary ones)? *git* isn't good at version control of binary data. Is there some way they can be either downloaded or generated as part of the notebook? If not, and they need to be there, then that's fine.

**Comment by kbarnhart** [comment]
@mcflugen a related comment, many of these files are also in landlab/tests/io/shapefile/data.

The files are shapefiles... It is very unlikely they will change (though I 100% agree about minimizing binary/data files)

Is there a better way for both parts of the code (shapefile tests and notebooks) to refer to the same data, other than a long path in notebooks and/or test scripts)

**Comment by mcflugen** [comment]
@pfeiffea @kbarnhart One solution is to move the data files into *landlab* (under something like *landlab/components/network_sediment_transporter/data*) and include them with a *landlab* installation. We would then need a new function that would get the example data files and copy them to a folder where the user could run the example.

**Comment by mcflugen** [comment]
@pfeiffea Another question concerning the binary data files. Do you know if they are tied to any specific platform (i.e. 32 vs 64 bit, big-endian vs little-endian, etc.)?

**Comment by pfeiffea** [comment]
I believe not.

Allison Pfeiffer
Assistant Professor
Western Washington University
Geology Department
Office: ES 339, website<https://sites.google.com/site/wwugeomorph/home>
Pronouns: she/her

**Comment by kbarnhart** [comment]
@mcflugen I like you .get_example_data idea. However, I think its better suited to live in landlab/io/shapefile. Mostly because other applications beyond NST might want to use similar example data. 

Do you have bandwidth to take a stab at this? If not, I can carve out some time (probably tomorrow).

Regarding details of file formats. My experience is that shapefiles are totally fine cross platform so long as you always move all of the required files. Its is now a pretty standard vector data file type. Just looks weird when you see all the extensions beyond .shp that GIS programs hide... 😄 

Wikipedia has a list of details of these files, including endian info. 
https://en.wikipedia.org/wiki/Shapefile

**Comment by mcflugen** [comment]
@kbarnhart I'll take a stab at this.

@pfeiffea The data in `tests/io/shapefile/data` is significantly smaller than that in `notebooks/tutorials/network_sediment_transporter/data` (412kB vs 44MB). The notebooks appear to run using just the data in the tests folder. Is it ok if I only include the data files from `tests/io/shapefile/data`? 44MB is quite a lot to include in a git repository.

**Comment by jonczuba** [comment]
@mcflugen, @kbarnhart, @pfeiffea 

In landlab\notebooks\tutorials\network_sediment_transporter\data

We only need the network and nodes. I see that there is a DEM and hillshade for the Methow, and in the Miscellaneous folder there are a lot more files for a few other basins that are not needed. 

The only things I think we need to keep are the MethowSubBasin_Nodes_4.XXX associated files and the /Miscellaneous/Methow_Network.XXX associated files. These are the nodes and links used in the tutorial. You can do a quick check in the network_sediment_transporter_shapefile_network.ipynb to verify that these are the two files loaded. Everything else in this folder can be deleted. These are the exact same files (with the addition of a basin boundary) kept in landlab\tests\io\shapefile\data.

**Comment by mcflugen** [comment]
@jonczuba Thanks! So we don't need the *MethowSubBasin.shp* files (the ones without the *_Nodes_4* suffix)?

@kbarnhart, @pfeiffea I've moved the data files around and added a new class to help manage *landlab* example data. This is pfeiffea/landlab#25. If you could please have a look and let me know what you think, that would be great. If it looks ok, I think @pfeiffea will have to merge it into this branch.

**Comment by pfeiffea** [comment]
@mcflugen this looks great to me. @kbarnhart, do you agree? If so I can go ahead and make the merge of [pfeiffea#25](https://github.com/pfeiffea/landlab/pull/25)

Thanks for catching the unnecessary DEM, @jonczuba

**Comment by kbarnhart** [comment]
Looks good to me. Nice work @mcflugen !

**Comment by jonczuba** [comment]
@mcflugen, @pfeiffea I think the MethowSubBasin.shp files (without the nodes suffix) can be deleted as well for compactness. This file is the watershed boundary that is never loaded in and shown. We will want to load boundaries like this (or other shapefiles) in in the application of the code to display other relevant things, but this is not necessary to demonstrate the code functionality.

**Comment by mcflugen** [comment]
Thanks all! I just removed the *MethowSubBasin* shapefile files in that pfeiffea#25, so it should be ready to go now.

**Comment by pfeiffea** [comment]
Done!

Allison Pfeiffer
Assistant Professor
Western Washington University
Geology Department
Office: ES 339, website<https://sites.google.com/site/wwugeomorph/home>
Pronouns: she/her

**Comment by kbarnhart** [comment]
Thanks for getting this all to work @mcflugen !

**Comment by kbarnhart** [comment]
🎉 !!!! thanks @pfeiffea for leading this effort! very excited that NetworkSedimentTransporter is in Landlab. 

I just tested compiling the JOSS manuscript over at http://whedon.theoj.org and it doesn't look like it quite compiles. So I think we need another PR to fix that before we can make the 2.1 release.

**Comment by pfeiffea** [comment]
And thanks to you, @kbarnhart, for your persistence and patience guiding @jonczuba and I through the process. I am truly grateful for you and @mcflugen. Now... on to do some science with this thing!

**Pull request merged**
