### PR TITLE
Siccar point/accel lake mapper

### PR DESCRIPTION
**Pull request by SiccarPoint**
This PR very significantly accelerates the lake mapper using a cfunc for a key method.

Performance increases are very marked for larger grids: I'm getting a >20-fold acceleration for a rerouting over a 1000x1000 grid of random numbers. (i.e., ~1h -> ~3 mins).

Also incorporates some light documentation work.

I suspect this will need pulling into the v.2 dev, but not sure how this will work.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@SiccarPoint looks good to me (except for small lint)

🎉 🎉 20x speedup! wahoo!

re: 2.0, the way I've handled this for everything else is to just create a new PR that brings these changes into that branch. Since we are now squash-merging this is done just by cherry picking the single merged commit. I've been doing this for all the PRs, so you don't need to do a thing.

**Comment by SiccarPoint** [comment]
OK, I got the primary lint error. However, the linter is still complaining about unused imports of the cfunc - which is manifestly not true. Ideas?

**Comment by mcflugen** [comment]
@SiccarPoint You import `find_lowest_node_on_lake_perimeter_c` twice, once at the top of the file, and then further down in `test_find_lowest_node_on_lake_perimeter_c`. Both of the linter errors are due to this.

**Comment by SiccarPoint** [comment]
thx

**Comment by DavidLitwin** [comment]
Hi @SiccarPoint and @kbarnhart, what is the status of getting this merged into LL2.0? It would be very helpful to me if it were available soon!

**Comment by kbarnhart** [comment]
@DavidLitwin - @SiccarPoint is the person to answer your question. I'll let him respond.

**Comment by SiccarPoint** [comment]
I was under the impression this was already merged before the LL2 version increment... Apparently not I guess.

Will resolve conflicts ASAP

**Comment by DavidLitwin** [comment]
Thank you @SiccarPoint!

**Comment by SiccarPoint** [comment]
Right, I think that will solve it. Could someone review and merge assuming it all passes?

**Comment by kbarnhart** [comment]
@SiccarPoint @DavidLitwin I can review and merge (and assist as need be).

**Comment by DavidLitwin** [comment]
@SiccarPoint there was an issue with the location of the cfuncs file in the testing script that I just corrected. Hopefully everything passes now.

**Comment by DavidLitwin** [comment]
@kbarnhart everything is passing but the docs... Can you review and approve?

**Comment by kbarnhart** [comment]
Tests pass except for a doc link check fail on the newsletter signup (https://github.us18.list-manage.com/subscribe?u=2db7cea82e3ea40fcf4c91247&id=b9bad233c7) which I've verified to be good... 

Looks good @DavidLitwin thanks!

**Pull request merged**
