### PR TITLE
SiccarPoint/component modernisation

### PR DESCRIPTION
**Pull request by SiccarPoint**
This pull modernises the style of the LinearDiffuser and SedFluxDepIncision components, as well as a few functionality enhancements (e.g., diffuser now handles spatially variable diffusivity).

### CODE REVIEW

**Comment by SiccarPoint** [comment]
@mcflugen : this bad boy has started throwing int64 related errors in the Windows builds, though I didn't touch the parts of the code where they're occurring. Hopefully they'll vanish on merge to Master, but if you think they won't, please jump in beforehand.

**Comment by mcflugen** [comment]
@SiccarPoint: It doesn't look like they'll be fixed with the merge. It should be an easy fix in `lake_mapper.py`, though. `pit_node_ids` just needs to be change to be an array of `int`.

**Comment by mcflugen** [comment]
@SiccarPoint: your changes should work but it's better to use `as_id_array` (`from landlab.core.utils import as_id_array`) to avoid unnecessary copies.

**Comment by SiccarPoint** [comment]
I'm not familiar with how that works... Could you dive in?? (Sorry...)

**Comment by SiccarPoint** [comment]
...hang on, I got this - just wrap the output, right? And it's an in-place operation, not a copy?

**Comment by mcflugen** [comment]
Correct. The problem is that `astype` creates a copy by default. So the following is true,
```python
>>> x = np.arange(12, dtype=int)
>>> y = x.astype(int)
>>> y is x
False
```

**Comment by mcflugen** [comment]
@SiccarPoint: Sorry. I had already pushed the change before I saw your message.

**Comment by SiccarPoint** [comment]
...but, in contrast:
```
>>> x = np.arange(12, dtype=int)
>>> y = as_id_array(x)
>>> y is x
True
```
? If so, that's great to know about.

**Comment by gregtucker** [comment]
Looks good, I am going to merge

**Comment by SiccarPoint** [comment]
No worries. Good to know my code is verbatim same as yours!

**Comment by gregtucker** [comment]
...after the tests complete

**Comment by mcflugen** [comment]
Yes, `as_id_array` should just return the same array if it doesn't need to make a copy when converting to `int`.

**Comment by mcflugen** [comment]
@gregtucker: Yes, please wait for the AppVeyor tests to complete. I canceled some redundant builds but there's still a bit of a queue so it might take a while.

**Comment by gregtucker** [comment]
Looks as if there's a Travis failure here -- just one of the tests, and maybe it timed out on build. Will it be automatically run again?

**Comment by mcflugen** [comment]
I restarted the build. Things look good. The AppVeyor builds are still running but it looks like they'll all pass.

**Pull request merged**
