### PR TITLE
Adding component documentation

### PR DESCRIPTION
**Pull request by kbarnhart**
To address Issue #629 

Tagging @margauxmouchene @mcflugen @cmshobe @Glader011235 @gregtucker since you've created some of these components 

@margauxmouchene I included the `TransportLengthHillslopeDiffuser` and @mcflugen I included  `Layers`. Let me know if they are not ready to be part of the main documentation and I'll remove them. 

This PR attempts to update the component documentation and includes the following components:

FlowAccumulator and all FlowDirectors
ExponentialWeatherer
DepthDependentDiffuser
DepthDependentTaylorDiffuser
TaylorNonLinearDiffuser
TransportLengthHillslopeDiffuser
ErosionDeposition

@mcflugen let me know how I should attempt to check if this doesn't break the docs since in PR #633 you said that we are no longer testing that the docs build. I've tested it locally and other than the docstrings on `__init__` not showing up it seems to work OK. Let me know how you guys dealt with the `__init__` issue before -- was it just to change the location of the docstring text?

### CODE REVIEW

**Comment by margauxmouchene** [comment]
Thanks @kbarnhart! The documentation for the transport-length hillslope diffuser is ready to go.

**Comment by kbarnhart** [comment]
@mcflugen Looking at #587 I see that `autoclass_content = 'both'` in `conf.py`. Fixes the `__init__` issues. spiffy!

**Comment by kbarnhart** [comment]
@mcflugen 
OK of I merge this?

**Comment by mcflugen** [comment]
Looks good to me. The only tiny thing I would say is that Sphinx spits out a warning whenever it sees a heading underlined with the wrong number of characters. So instead of,
```
Layers
==========
```
it likes
```
Layers
======
```
I would eventually like our docs to build without any warning messages (perhaps wishful thinking?) so may as well fix these things as they come up.

**Comment by mcflugen** [comment]
@kbarnhart, Thanks!

**Pull request merged**
