### PR TITLE
Fix the ordering of elements around another element

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request is an experiment to standardize the ordering of one type of element around another type of element. For example, links around a node, and nodes around a node. Previously, node neighbors were ordered counter clockwise starting at the eastern node but links were ordered clockwise starting at the southern link.

This address, at least partly, #156 and #191.

**This is definitely not complete** so not at all ready to be merged.

Added a new property, `links_at_node`, that is an `nnodes x links_per_node` matrix ordered as ENWS. This is intended to replace the method `node_links` that returned a `links_per_node x nnodes` array of links ordered SWNE.

Changed components that used `node_links` to use the `links_at_node` property.

I found two possible bugs in:
* `stream_power.py` (line 286)
* `tl_fluvial_monodirectional.py` (line 440)

In both cases they use `node_links` as though it is an array when it's actually a method.

### CODE REVIEW

**Comment by mcflugen** [comment]
I think this is ready to go. The ordering of one thing around another should how follow E, N, W, S. (so, neighbor nodes around a central node, links touching a node, etc.). I would like to merge this before the big merge of @gregtucker's `sort-links` branch. I hope it will make things less painful.

I know everyone's busy with AGU but, maybe (?), @jadams15's could have a look?

**Comment by SiccarPoint** [comment]
Yesterday, I realised another place these changes need to happen: in the grid edge BC setters. These normally do something like (bottom_is_closed, left_is_closed, top_is_closed, right_is_closed). I *always* have to check this order when I use them, so these are a prime candidate for updating.

BUT

These are also used extensively in the various examples, including in the drivers repository. We’ll have to be careful with these.

**Comment by mcflugen** [comment]
Already done (as of like a minute before your post).

I actually think they should be deprecated now. It's much easier and more readable to do something along the lines of,
```python
grid.status_at_node[:, 0] = CLOSED_BOUNDARY
```

**Comment by SiccarPoint** [comment]
Disagree, at least for now. These are very helpful one-line methods in real use cases which we should retain. Any alternative requires deeper knowledge of LL for a user; e.g., your example requires the user either to know how to reshape the grid as a view, or to know where LL stores its lists of edge nodes, and also to know how the import the NODE_STATUS values. Which as of a couple of days ago, was still really opaque in the master. Iff we could sort out easy access to the edge IDs, I’d feel better about:

```
>>> mg.status_at_node[mg.nodes_at_left_edge] = CLOSED_BOUNDARY
```

Did you trawl all the examples for uses? Impressive. (And the Drivers repository…?)

Also, final point of order - I’m 80% of the way through setting up unit tests for many of the components. I’m very keen to get these committed to master before any of your or Greg’s changes get pulled. I’m suspicious things like this could easily be breaking components, and we would have zero idea until it was too late.

**Comment by mcflugen** [comment]
And just for further increase the confusion to max, `set_inactive_boundaries` (which is deprecated) is SENW while its replacement, `set_closed_boundaries_at_grid_edges` is SWNE.

**Comment by SiccarPoint** [comment]
Re ordering changes... yeah. That's annoying. But at least most (NOT ALL) of the existing BC uses are symmetrical.

**Comment by mcflugen** [comment]
Agreed. I'm fine keeping those methods. *However*, the fact that you (and me and probably everyone) always has to go back to the docs to figure out the ordering might be a sign we need to change something to make it more clear. Sticking with ENWS helps, certainly. Maybe add keywords?
```python
def set_closed_boundaries_at_grid_edges(east=True, north=True, west=True, south=True)
```

**Comment by mcflugen** [comment]
As you pointed out, my example wasn't totally correct since `status_at_node` is flat. I just meant setting the boundary conditions through the `status_at_node` attribute. So, I agree,
```python
grid.status_at_node[grid.left_edge] = CLOSED_BOUNDARY
```
would by the way to do it.

**Comment by SiccarPoint** [comment]
Yes to keywords. That’s a great plan.

Let’s retain both possibilities for now. There’s little harm in having two ways to do it. (yeah, I know, not pythonic…)

Also, we can’t actually do mg.left_edge can we? Or rather, I guess, mg.nodes_at_left_edge. Would be good to have (not squirreled away in sgrid, or whatever).

**Comment by mcflugen** [comment]
No, we can't do that currently. I think adding something like that would make sense, though.

**Comment by jadams15** [comment]
re: nodes at left edge, we do have a function call for that, yes? mg.left_edge_node_ids() unless it has been changed... I struggle to keep up with all of this (very important, very useful) progress!

Eric - I can try to take a look tonight. Will also prioritize finishing up the link tests today. It has been super hectic this week, trying to play catch-up after our very productive two days with Gilles Brocard last week and running my AGU stuff.

**Comment by SiccarPoint** [comment]
This does exist, yes, but I can never find it when I need it because it is named so oddly! Should definitely be nodes_at_left_edge, and a property not method.

Again, please hold off until my tests are in! But that should be by this evening. I’ll let you know.

D

**Comment by mcflugen** [comment]
@SiccarPoint: yes I will definitely hold off until you give the go-ahead.

@jadams15: you are correct, we do have `left_edge_node_ids`. I agree that it's oddly named and should be renamed and, I think, probably be a property and an iterator (not an array). Please have a look whenever you have a chance. No rush. Tonight would be great!

I prefer the sound of just `grid.left_edge` but it might be more in line with the rest of our naming conventions to use `grid.node_at_left_edge`.

**Comment by SiccarPoint** [comment]
Problem with left edge is left edge what? We’ll probably need one for e.g. links eventually.

Would a iterator still work with:

```
mg.status_at_node[mg.nodes_at_left_edge]
```

?? (I’ve never got this)

**Comment by mcflugen** [comment]
I agree. Although `left_edge` might sound good, it's not clear if it's referring to nodes, links, cells, etc.

Yes, I think we should somehow get an iterator to work. For instance the following works,
```python
grid.status_at_node[xrange(3)] = CLOSED_BOUNDARY
```
and `xrange` is an iterator. In any case, I don't think we have to carry around another array.

**Comment by SiccarPoint** [comment]
Sweet. As long as it works!

**Comment by jadams15** [comment]
I built counterparts for links. they're separated into vertical and horizontal functionality. things like "left_edge_vertical_links()". they'll need to be renamed eventually as well!

**Comment by mcflugen** [comment]
Great. I guess a better name for them would be `links_at_left_edge` (do you ever really need horizontal links at the "left" edge?). Or maybe "edge" is redundant? `links_at_left`?

Should we be using "right", "top", "left", "bottom" or "east", "north", "west", "south"?

**Comment by jadams15** [comment]
yes, you'll need horizontal links at the left edge if you want to set FIXED_LINK boundary status. 

I think I prefer to have "edge" for no reason other than I like the way it sounds, and in some of the boundary status functions we use that terminology: set_closed_boundaries_at_grid_edges(). 

The latter question: I have no strong preference. right/top/left/bottom are used in many places in the code that would need to be eventually changed.

**Comment by SiccarPoint** [comment]
Top/bottom etc a bit more general - think for example of the CA in use as a vertical section, where it really is left/right/up/down. But whatever.

**Comment by mcflugen** [comment]
I agree. "right", "top", "left", and "bottom" seems more general and standard. I don't know of anyone who refers to the east edge of a raster image, or the south row of a matrix.

**Comment by SiccarPoint** [comment]
OK guys, pull request in. From my end, everything is passing fine, so hopefully this is a quick, clean merge.

I’m probably going to be largely offline for the next few days, so if anything needs attention that a reviewer can’t just fix on the fly, it might be better to note the issue, do the merge anyway, and I’ll fix it in master next week.

Happy Thanksgiving, all.

D

**Comment by mcflugen** [comment]
Alright. This is ready to go again. I've rebased to include @SiccarPoint's new tests. I modified them to use CCW ordering (for setting the node status along edges) and they are now all passing.

**Comment by gregtucker** [comment]
This looks good to go to me. @mcflugen, do you want to merge or shall I?

Great that this eliminates the use of "inactive boundary" (as in set_inactive...) in base.py, but it still exists in raster.py, right? Has anyone removed it since this PR? Or should we create a new issue to get rid of it in favor of set_closed_boundary...?

**Comment by mcflugen** [comment]
Thanks, @gregtucker! I'll merge it. I still would like to wait to merge this after #222, which @saisiddu is looking at, just to minimize the disruption to @lgelb.

I'm not certain, but I think the "inactive boundary" stuff you're talking about in `raster.py` *may* be taken care of with #210. If not, let's incorporate it through another issue and pull request.

**Comment by saisiddu** [comment]
I have merged the pull request assigned to #222.  Everything looks fine. Thanks Eric! I might start using write netCDF immediately. That way, I will not have to deal with multiple files lying around in my 'outputs' folder. [😊]


________________________________

**Pull request merged**
