### PR TITLE
Barnhark/merge945

### PR DESCRIPTION
**Pull request by kbarnhart**
@mcflugen Here is the equivalent for #945 on v2dev

A couple notes on keeping v2dev up to date. I think the best workflow is:

squash-merge into 1.0 master
locally checkout v2dev, create a branch, and then cherry-pick the squashed commit.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen all the travis osx builds fail on checking out the branch...

```
$ git checkout -qf f9b273f9191d48274ef5f0557e1d85e3a395163c
fatal: reference is not a tree: f9b273f9191d48274ef5f0557e1d85e3a395163c
The command "git checkout -qf f9b273f9191d48274ef5f0557e1d85e3a395163c" failed and exited with 128 during .
```

thoughts?

**Comment by kbarnhart** [comment]
@mcflugen can you approve?

**Comment by jmdelvecchio** [comment]
Hi, I don't know if this is where I'm supposed to write this, but - when can I tell when all changes to DDD have been added to Landlab and I can update? (which involves uninstalling and installing, if I'm not a developer?) I've been lurking a bit cause I'm eager to test the new stuff out!

**Comment by mcflugen** [comment]
@kbarnhart Sounds good. Sorry, I thought I had already approved this.

**Comment by mcflugen** [comment]
@jmdelvecchio I'm not sure what *DDD* is. However, I think we'll have a new release in the next couple of days, which might be what you're looking for? It would have everything that's currently on the developer version. You should just have to update, not uninstall/reinstall but either way should be fine.

**Comment by jmdelvecchio** [comment]
> @jmdelvecchio I'm not sure what _DDD_ is. However, I think we'll have a new release in the next couple of days, which might be what you're looking for? It would have everything that's currently on the developer version. You should just have to update, not uninstall/reinstall but either way should be fine.

The depth dependent diffuser that Rachel changed and Katy is merging (I guess?). And i"m following the instructions at the bottom of https://landlab.github.io/ for the Anaconda distribution. Is there a way to update besides uninstalling if I'm not forking things (I think, again??)?

**Comment by kbarnhart** [comment]
@jmdelvecchio Sounds like you installed via conda (e.g., `conda install landlab -c conda-forge`). If this is the case, you need to wait until there a new release of landlab. After that you should be able to update via `conda update landlab`. 

Right now the changes we made are presently on the `master` branch of landlab. This version of the code is available for those who want the bleeding edge of landlab and use the [developer install](https://github.com/landlab/landlab/wiki/Installing-Landlab-from-source-code-(%22developer-install%22)).

If you need us to make a release with these new changes in it, the best thing to do is request that by making an [Issue](https://github.com/landlab/landlab/issues/new).

**Pull request merged**
