### PR TITLE
Fix Flats in Accumulate-to-Multiple, BC and closed node issues in Dinfinity

### PR DESCRIPTION
**Pull request by kbarnhart**
This starts to address #802 

Not done yet.

### CODE REVIEW

**Comment by kbarnhart** [comment]
Now ready for review. 

@SiccarPoint and @amanaster2 could you both review this pull request (I can only formally add @SiccarPoint in GitHub).

This addresses a few different Issues (#802, #667, and #811). 

- It makes sure that the FlowDirectorDINF and FlowDirectorMFD work correctly with perfectly flat terrain (Issue #802)
- It modified FlowDirectorDINF to correctly handle flow next to closed boundary nodes correctly (Issue #667) and makes it so it does not appear the flow is coming from closed nodes (#811). 

I've added a number of new tests for MFD and Dinf that provide analytical tests to both of these flow directing methods (for sloped and flat surfaces, with and without closed boundaries). This is where I'd focus looking.

**Comment by kbarnhart** [comment]
@amanaster2 - @saisiddu recommended I make some comments being a bit more specific about what I'd like you to do (if you are able). 

1) check out this pull request branch and see if it fixes the problem you posted in #811 
2) look at the new tests you can see them most easily be clicking the "files changed" tab above. I built each of these tests as an "analytical" solution -- a situation in which I think I know what the right answer is. I'd be very interested for you and @SiccarPoint to determine if you think these tests are correct. If you think there is a place were I got the test wrong, or where another tests is needed, just make a comment. 

Any amount of either of these items would be great! Thank you!

**Comment by amanaster2** [comment]
@kbarnhart Okay, great. Thanks for the specificity! I will try to do so this week, but I'll be going into the field Wed-Sat. If not this week, I'll look at it early next week.

**Comment by kbarnhart** [comment]
@amanaster2 sounds great! thanks for having a look! early next week is totally fine.

**Comment by kbarnhart** [comment]
@SiccarPoint thanks@ @amanaster2 let me know what you think.

**Comment by amanaster2** [comment]
@kbarnhart Everything looks good to me!

**Pull request merged**
