### PR TITLE
Fixing ErosionDeposition so that it can handle negative slopes with n<1

### PR DESCRIPTION
**Pull request by kbarnhart**
Addresses #522 

@gregtucker @cmshobe let me know if you have comments.

### CODE REVIEW

**Comment by gregtucker** [comment]
This looks good to me. One potential issue though: setting flooded nodes to S < 0 could have the unintended side effect of allowing erosion at nodes that are flooded but have S > 0. In theory, the solver should prevent S < 0 at non-flooded nodes, though the existence of a minimum dt could allow S < 0 to happen occasionally. Is there a way to mark "flooded" nodes as the set of those identified as flooded by the lake mapper as well as any additional ones with S < 0?

**Comment by kbarnhart** [comment]
Good point @gregtucker . I'll fix that.

**Comment by kbarnhart** [comment]
@gregtucker Now this should maintain the original flooded nodes and add any "new" flooded nodes with slopes of less than zero.

**Comment by gregtucker** [comment]
Cool, thanks. I'll merge once tests finish.

**Comment by kbarnhart** [comment]
Thanks!

**Pull request merged**
