### PR TITLE
Address Issue 774

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR starts to address Issue #774 

I've removed the duplicated field names and the tests pass (locally). 

There are a few things that still need to be done (@SiccarPoint feel free to add commits to this PR if you are so inspired). 

As best I can tell, three fields that matter here are: flow__receiver_node, flow__link_to_reciever_node, and topographic__steepest_slope.

The two big things that I think we need to do are:

a) write the tests for the new NotImplementedErrors I've made (this is easy, I just didn't get a chance)

b) identify all other components that use these three fields, and either:
    - write a test that demonstrates that they can work with a route to multiple
    - raise a NotImplementedError and write a test for that. 

This one is harder and will take some consistent checking across the code base.

I propose that we brainstorm what all the components are first and then move forward from there.

### CODE REVIEW

**Comment by SiccarPoint** [comment]
No worries - this isn't causing any crucial problems, so we can happily kick this down the road.

A little light searching indicates the key components to look at will be:
`draininage_density`
`erosion_deposition`
`generalised_erosion_deposition`
`lake_mapper`
`lake_mapper_barnes`
`space`
`channel_steepness`
`stream_power`
`fastscape_stream_power`
`stream_power_smooth_threshold`
`sed_flux_dep_incision`
`transport_length_hillslope_diffusion`

And the various `flow_accumulator`s and `flow_director`s (obviously). Utils are:

`channel_profile`
`drainage_plot`
`flow_distance`
`source_tracking_algorithm`
`watershed`

I suspect the fast solution here might be to by default introduce the assertions, unless we (realistically, you, as designer of the route-to-manys?) know for a fact the component is happy with route-to-many. AFAIK they are all guaranteed to work with one-to-one, and we can relax this constraint piecemeal later.

**Comment by SiccarPoint** [comment]
OK, this looks great. Only comment might be that you've added a couple of helper properties in the flow directors as part of this (viz. `node_steepest_slope, and `link_to_flow_receiving_node`), and I don't believe (?) they're tested. Clearly these are trivial, but it's lines we aren't covering as-is... I suspect the same probably applies to their adjacent, existing friends (e.g. `proportions_of_flow`).

I assume you have the failing tests here in hand.

Good to go when you are.

**Comment by kbarnhart** [comment]
Thanks @SiccarPoint! I'll add those tests (and merge if all passes).

The travis errors seem to have to do with issue #782 and should be resolved on this branch soon.

**Comment by kbarnhart** [comment]
@SiccarPoint I took this opportunity to bring the `flow_accum` and `flow_director` component submodules to 100% coverage. Thanks for pointing out the coverage gap.

**Pull request merged**
