### PR TITLE
SiccarPoint/D4routing

### PR DESCRIPTION
**Pull request by SiccarPoint**
This pull implements the ability to specify D4 style routing for lake fill and sink fill algorithms. It also modifies the basic sink fill algorithm for speed and generality.

### CODE REVIEW

**Comment by SiccarPoint** [comment]
@jadams15 Took the liberty of assigning this to you Jordan, as I know you want the D4 stuff! If you're super busy, no worries. Note however this comes chronologically after #173, so it would be best if that gets merged first for stability... Think this works as a stand-alone though (i.e., I merged in the key changes from that pull too).

**Comment by SiccarPoint** [comment]
Unclear why this isn't passing all checks. Nose tests look good from my end, and it appears to only be *one* of the UNIX builds. Not seen a fail like this before?

**Comment by SiccarPoint** [comment]
(Eric said this is probably a connectivity issue at Travis' end, so it's probably OK)

**Comment by jadams15** [comment]
I very much need this! and am happy to go over it. I might contact you later today via e-mail. Having issues getting OF component to run using topography generated using d4 flow router. It doesn't look like there are any changes to that here. It could very well be a problem on my side of things. I just can't. squash. this. bug!!!! Hopefully by this afternoon's call I'll have solved both problems.

**Comment by jadams15** [comment]
OK. Gonna merge! Looks good. As a reminder I reviewed: PEP8 styling, reviewed docstrings for clarity (there is one minor typo in lake_mapper.py line 108, but can be fixed once merge is done) and made sure there were unit tests (which, bravo! very comprehensive. I like.)

**Pull request merged**
