### PR TITLE
add additional references for 2020/21

### PR DESCRIPTION
**Pull request by gregtucker**
Add references to papers_presentations.rst

### CODE REVIEW

**Comment by gregtucker** [comment]
@mcflugen could you give this a 👍 or 👎 ? Should be simple, it's just an .rst file :)

**Comment by gregtucker** [comment]
Ah wait, forgot one...

**Comment by gregtucker** [comment]
Ok, there it is, last one added

**Review by mcflugen — APPROVED** [review]
👍 Looks good to me @gregtucker! So many references!

**Pull request merged**
