### PR TITLE
Address Issue 779: Travis fails due to the pytest version

### PR DESCRIPTION
**Pull request by kbarnhart**
Only thing changed here is the pytest version in the `.conda-recipe/meta.yaml` and the `.travis.yaml` files. 

Should address #779.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen OK to merge this? at this point it only changes the version number.

**Comment by mcflugen** [comment]
> OK to merge this?

Sure. However, version 3.7.4 just came out, which should fix this problem. Maybe check if 3.7.4 works first?

**Comment by kbarnhart** [comment]
Since 3.7.4 is now out (and is the latest version), just removing the version info should work, right?

**Comment by mcflugen** [comment]
Correct. I don't see why we should specify the version number any more.

With pytest working again, there now shouldn't be any need to merge this, correct? I think we can close this pull request.

**Comment by kbarnhart** [comment]
But, I agree, no need to merge this as 3.7.1 works from your PR #778.

Eventually we can test if removing the version number works.

**Pull request closed without merging**
