### PR TITLE
Reverting Channel Profiler to commit 35db1f199037b40f0cdd637f39384c6e61042f15

### PR DESCRIPTION
**Pull request by kbarnhart**
Component tutorial passes locally. 

I chose not to deprecate it yet, because the replacement is in progress. Will deprecate as part of the PR with the replacement.

### CODE REVIEW

**Comment by kbarnhart** [comment]
Addresses Issues #690 #691

**Comment by kbarnhart** [comment]
Ahhh. @SiccarPoint , I tested `master` instead of `next`, which must be why tests passed for me. 

Other changes I made to the component tutorial had to do with the FlowAccumulator, which are independent. 

I'll put in a new PR for the tutorials repo to. Thanks for catching that.

**Comment by kbarnhart** [comment]
@SiccarPoint can you tell me exactly which tutorials branch and exactly which landlab branch you see errors on? 
I'm having a hard time replicating failures.

**Comment by kbarnhart** [comment]
@SiccarPoint , yes, I would have focused on making the `analyze_channel_network_and_plot` method work identically. 

The channel_nodes function did change, though.
```python
# my version
def channel_nodes(grid, starting_nodes, drainage_area, 
                  flow_receiver, number_of_channels=1, threshold=None, main_channel_only=True):
# old version
def channel_nodes(grid, steepest_nodes, drainage_area, 
                  flow_receiver, number_of_channels=1, threshold=None):

```
Something else errors, though -- otherwise the component tutorial indexing error wouldn't have come up.

I can't make finishing this component a high priority right now. So I'll just be able to set tutorials back so they run with this reversion.

**Comment by SiccarPoint** [comment]
I was looking at the release tutorials branch, where at the end there's:
```
>>> profile_structure, distances_upstream = prf.analyze_channel_network_and_plot(mg,create_plot=False,
                                                                             main_channel_only=False,
                                                                             number_of_channels=7,
                                                                             threshold=0.01)
>>> prf.plot_channels_in_map_view(grid=mg, profile_structure=profile_structure)
```
However, I note this isn't in the master. Also, the website appears to be looking at the master version, not the release? That seems odd to me.

**Comment by kbarnhart** [comment]
@SiccarPoint thank you! Yes, I'll fix that to be back how it was. 

Regarding the branches... @mcflugen will have to verify that I've gotten this right...

`release` tracks the current landlab/landlab `release`
`next` tracks landlab/landlab `master`
`master` tracks .... not sure.... 

I'm pretty sure that my confusion comes from the fact that recently we switched from merging new tutorials into `next` instead of `master`.

**Comment by kbarnhart** [comment]
Tutorials repo updated here: https://github.com/landlab/tutorials/pull/24

**Comment by kbarnhart** [comment]
@mcflugen I think that deleting it would make sense. I made a note of this in what seemed to me was the right place (https://github.com/landlab/tutorials/issues/8)

**Pull request merged**
