### PR TITLE
Nicgaspar/watershed boundary condition

### PR DESCRIPTION
**Pull request by nicgaspar**
- deleted from components folder dem_boundary_conditions
- deleted from components folder simple_power_law_incision
- added a halo option to read_esri_ascii in esri_ascii.py
- added a default nodata_value of -9999. in read_esri_ascii in esri_ascii.py
- added an error in read_esri_ascii if data passed in is not the same size as the grid
- added move_origin to base.py
- added method set_watershed_boundary_condition to RasterModelGrid class in raster.py
- added method set_watershed_boundary_condition_outlet_coords to RasterModelGrid class in raster.py
- added method set_watershed_boundary_condition_outlet_id to RasterModelGrid class in raster.py
- changed all doc tests in base.py and raster.py to instantiate RasterModelGrid as rmg = RasterModelGrid((rows, cols)) instead of RasterModelGrid(rows, cols)
- added doc tests to all new methods and capabilities
- add new unit tests for read_esri_ascii

### CODE REVIEW

**Comment by jadams15** [comment]
@nicgaspar: I am going to merge this, but I have two questions:

1) what is the file landlab/landlab/io/test_output  (there is no file type)? It says this was added 3 days ago but I can't figure out why. Did I miss something?

2) what is the difference between landlab/landlab/io/tests/data/hugo_site.asc and landlab/landlab/io/tests/data/#hugo_site#.asc? 

Do we need either or both of these? It doesn't seem to be critical for me to remove them, but I wanted to ask if we need them. Otherwise, ready to rock! Merging now.

**Comment by mcflugen** [comment]
@jadams15: I think both of those files can go. One is an emacs temporary file and the other is empty.

**Comment by nicgaspar** [comment]
Good catch Jordan. Sorry about that. Neither is needed (test_output or file with #). They were just created while I was testing. My file editor makes weird backup files with the #'s.

Should I delete them?

**Comment by jadams15** [comment]
I thought I had merged last night, but apparently did not? anyway. removed the offending files. merge complete!

**Pull request merged**
