### PR TITLE
Gt/kinematic extender

### PR DESCRIPTION
**Pull request by gregtucker**
New component that simulates extensional tectonics with a listric fault plane.

### CODE REVIEW

**Comment by gregtucker** [comment]
@mdpiper do you have time to review this PR?

**Comment by mdpiper** [comment]
@gregtucker Will do!

**Review by mdpiper — APPROVED** [review]
I installed the component (with a note on #1271), read through the code, ran the example blocks, ran the tests, and worked through the notebook. Everything is in good shape, and I learned a little bit about faulting.

**Comment by gregtucker** [comment]
merge with updated main

**Pull request merged**
