### PR TITLE
Redesign ListricKinematicExtender to use AdvectionSolverTVD

### PR DESCRIPTION
**Pull request by gregtucker**
### Description

This PR introduces a complete re-design of the `ListricKinematicExtender`. The previous version modeled the horizontal component of tectonic motion using a step-by-step intermittent shift algorithm in which topography and hangingwall thickness were shifted by one grid node whenever the accumulated displacement reached or exceeded grid-node spacing. This approach had the advantage of avoiding numerical diffusion, but it restricted the fault strike to align with a grid direction, and when coupled with flexural isostasy, caused spurious intermittent subsidence "events". The new version discards that approach in favor of using a numerical solution to the advection equation, which is now available in the `AdvectionSolverTVD` component. This has the disadvantage of introducing some numerical diffusion, but it eliminates the problem of subsidence events and allows much more flexibility in fault geometry and displacement. For example, the displacement rate field no longer needs to be uniform in space.

This is a change-breaking update. We would not normally break backward compatibility outside of a major release, but in this case, the component is a rather specialized and obscure one, and to the best of my knowledge no one but me is actually using it (however, if anyone reports a problem we can bring back the original with a modified name).

### Checklist

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [X] Add / update tests if necessary?
- [X] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Successful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by gregtucker** [comment]
Addresses issue #1635

**Comment by gregtucker** [comment]
Note: the notebook test fail is unrelated to this PR.

@alangston @kbarnhart @SiccarPoint @cmshobe @pfeiffea anyone feel like reviewing a PR for old times' sake?? Or any suggestions on who else in the community might be interested in taking a look at this slightly obscure tectonic-related component?

**Comment by gregtucker** [comment]
@taranguiz would you be interested in doing a quick review on this pull request? I can ask @mcflugen to look at the coding style, but I'd also love to get your perspective as a skilled tectonic geomorphologist: does the code and accompanying notebook basically make sense?

**Comment by pfeiffea** [comment]
@gregtucker I'm happy to chime in here once I get back to the office from field work (next week... hopefully). If nobody else is available beforehand, I'll do it then!

**Comment by taranguiz** [comment]
> 

@gregtucker I would love to look at it and help as much as possible with my limited coding knowledge. It would be a good learning exercise too. I'm not sure what to check first so I might need some guidance on that. I scheduled an office hour for tomorrow with the CSDMS team.

**Comment by gregtucker** [comment]
Last call for a review of this... 

Just updated with latest master branch. If tests pass and no one jumps in with a review, I will go ahead and merge.

**Comment by gregtucker** [comment]
Tests are all passing, so I'm going to be a cowboy and merge this... :)

**Pull request merged**
