### PR TITLE
Add contributing doc

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request offers an initial stab at writing a `CONTRIBUTING.md` document for landlab (GitHub will provide a link to it when users submit a pull request or open an issue). This is meant to be read by new landlab users who would like to contribute to landlab either through code (as pull requests) or a issues (bug reports, feature requests, etc.). It's not yet complete but I thought I would initiate the pull request so others can comment and offer changes and additions.

### CODE REVIEW

**Comment by gregtucker** [comment]
:heart: :heart: :heart:

Wonderful! Couple of tiny things:
o Line 39: helpful to remind readers how to find out their LL version
o Line 41: he => the
o Line 109: that => at

**Comment by margauxmouchene** [comment]
That's great!

In the 'Adding new components' section, you could add links to the ['Develop your own component' page](https://github.com/landlab/landlab/wiki/Develop-your-own-component) and [this tutorial](https://nbviewer.jupyter.org/github/landlab/tutorials/blob/master/making_components/making_components.ipynb).
[This page](https://github.com/landlab/landlab/wiki/Developing-with-github-and-git) is also very helpful to get started when contributing a component or submitting changes.

And how about a shortened version of this document on the [front page](https://landlab.github.io/#/) to clearly promote the collaborative nature of Landlab?

**Comment by kbarnhart** [comment]
I'm updating the User Guide at the moment.

**Comment by kbarnhart** [comment]
User guide on testing now updated. 

https://github.com/landlab/landlab/wiki/Develop-your-own-component#writing-docstring-and-unit-tests-for-your-component-or-utility

any comments more than welcome.

**Pull request merged**
