### PR TITLE
Add halo and add-to-grid for netcdf

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR addresses #866

### CODE REVIEW

**Comment by mcflugen** [comment]
👍 Looks good @kbarnhart. I added some tests for `add_halo` and also changed it's signature. I hope you're ok with it.

* I removed the `shape` argument. I think the user should just reshape the input array to what it should be (and now the only return value is the new array with the correct shape),
* `halo` is now a keyword with the default being `1`,
* changed `nodata_value` to `halo_value` as I thought that was more descriptive, I also made it a keyword,
* the default for `halo_value` is `None`, which means don't initialize the halo values.

What do you think?

**Comment by kbarnhart** [comment]
@mcflugen I have a couple of thoughts/questions:

1) I think the default halo should be of size 0, not 1. This is to keep consistency with `read_esrii_ascii` (and current behavior). 

2) I think it should stay as `nodata_value` (for consistency with the `read_esrii_ascii` function). Also, because eventually I think we'll handle the `nodata_values` better (see Issue #849). 

What do you think?

**Comment by mcflugen** [comment]
1. Having the default be `0` is fine, although for a function called `add_halo` I think it might be a bit surprising to have `add_halo(data)` not actually add a halo.

2. I guess I'm thinking about `add_halo` a little more generally than what it's being used for in this pull request. I don't think of the halo values as being *nodata*. As an example of them truly not being *nodata*, in the future, we could add additional ways of setting the halo values (for instance the fill values could be chosen to maintain some gradient, or wrap-around boundary conditions).

Right now, `add_halo` is only being used in `read_esri_ascii` and `read_netcdf` but I think it could be used much more generally.

**Comment by kbarnhart** [comment]
@mcflugen I totally misunderstood what you meant in the first comments... 🤦‍♀️ 

I like how you have modified `add_halo`! Assuming it passes, I think its good!

**Pull request merged**
