### PR TITLE
Siccar point/fix1296

### PR DESCRIPTION
**Pull request by SiccarPoint**
This short PR addresses #1296

### CODE REVIEW

**Comment by SiccarPoint** [comment]
@mcflugen The extensive Black checking is new to me here. What formatting have I violated!? And will it automatically fix on merge?

**Comment by mcflugen** [comment]
@SiccarPoint No, the formatting would not have been fixed with the merge. It was minor so I fixed it up (it was just a matter of combining two lines into one).

I'm not sure about the notebooks checks. I'll have to have a closer look.

**Comment by mcflugen** [comment]
@SiccarPoint The errors in the tests appear to be caused by a change in a new version of *xarray*—something that used to cause deprecation warnings now raises exceptions. I think I have a fix but will do that in a separate pull request.

**Comment by SiccarPoint** [comment]
@mcflugen Now have the xarray changes into the branch and everything is passing, so a polite bump for a very straightforward review...

**Comment by SiccarPoint** [comment]
Bump?

**Comment by SiccarPoint** [comment]
How can such a simple change to the code result in so much pain...??? So, seemingly I am now triggering CI tests on the documentation, which aren't triggered on the other PRs I'm trying to deal with, and these are failing on code I haven't been anywhere near. This is good to go, and urgent for Wednesday - @mcflugen can you explain/resolve??

**Comment by SiccarPoint** [comment]
Bizarrely, yesterday's failure on the docs appears to have gone away. As you are all snowed under, I'm merging this as admin. Hope this is OK...

**Pull request merged**
