### PR TITLE
Nst joss revisions

### PR DESCRIPTION
**Pull request by pfeiffea**
Hi @kbarnhart @mcflugen @jonczuba 

Here are the final edits to the NST for submission to JOSS. 

Notable changes: 
- There are now 3 options for setting active layer thickness. There are tests that cover all 3 of these options.
- The profiling and scaling notebook is thoroughly explained.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@pfeiffea this looks good to me. I have attempted delinting... which should help with passing tests.

**Comment by kbarnhart** [comment]
@mcflugen good to merge?

**Comment by kbarnhart** [comment]
(once this last round of tests are complete, presuming pass)

**Comment by kbarnhart** [comment]
Looks like the recent failures here were unrelated (had to do with tests/grid/test_grid_reference.py::test_move_reference_hex). 
I've restarted them.

**Comment by mcflugen** [comment]
👍 @kbarnhart Yes, this looks good to merge to me!

**Comment by kbarnhart** [comment]
@mcflugen I think we are ready for v2.2.0

**Comment by pfeiffea** [comment]
thanks @kbarnhart and @mcflugen -- let me know when v2.2.0 comes out and I'll re-submit promptly.

**Pull request merged**
