### PR TITLE
Fix issue #614 - Values not being cached

### PR DESCRIPTION
**Pull request by mcflugen**
@kbarnhart this pull request should fix the problem you identified in #614. Thank you so much for finding this! Good eye!

The problem was a small typo in the `cache_result_in_object` decorator, just as you thought. The decorator was checking for the cached value in the wrong place, so never found it, and so the value was always being recalculated.

Please see if this fixes your problem and if things are running at the same speed as they were before.

I also added some tests to make sure this doesn't happen in the future.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen this seems to have solved my problem (I get a ~40x speedup as a single timestep for my complex model goes from 41.462 seconds to 0.937 seconds).  

However,  I get 43 test failures when I build and test this branch (I'm on commit 7faad8cc61df2b414642df21ccaeb5990db87b22 which I believe is the most recent). I haven't been able to figure out the theme of the failures, so I've attached a text file that has the test output in it. Maybe you'll see the pattern...

[build_log.txt](https://github.com/landlab/landlab/files/1629824/build_log.txt)

My standard workflow for rebuilding is:

```python
python setup.py develop -u
conda install --yes --file=requirements.txt
python setup.py develop
python scripts/test-installed-landlab.py
```

**Comment by mcflugen** [comment]
@kbarnhart Thanks. I see the problem. It should be another easy fix.

**Comment by kbarnhart** [comment]
@mcflugen super!

**Comment by mcflugen** [comment]
@kbarnhart Not quite as easy as I thought but these latest changes should get us pretty close. Please have a look and see if they fix things for you.

**Comment by kbarnhart** [comment]
@mcflugen this passes tests on my computer and profiles to be nearly identical to the last profile test.

**Comment by mcflugen** [comment]
@kbarnhart Great! Since all the tests are passing on your machine and mine as well as AppVeyor, I think things are working.

Something strange is going on with our Travis builds that is causing them to fail. I've rerun builds that had previously passed and now they're failing so I don't think it has anything to do with these latest commits.

**Comment by kbarnhart** [comment]
@mcflugen I looked through the code and as best I can tell it looks good. I'm not super familiar with code you've modified related to testing and conda requirements, though.

I'm OK with this being merged whenever you think it is OK.

thank you!

**Pull request merged**
