### PR TITLE
Update NetworkSedimentTransporter joss paper

### PR DESCRIPTION
**Pull request by kbarnhart**
@pfeiffea @jonczuba @mcflugen 
[current_manuscript.pdf](https://github.com/landlab/landlab/files/4629948/ij9hunlffuastc8wb56d.pdf)

This PR finalizes the joss manuscript for the NetworkSedimentTransporter

Please comment/modify...

Also can see a current version of the PDF by using the Whedon wiget https://whedon.theoj.org/

### CODE REVIEW

**Comment by kbarnhart** [comment]
I fixed the error caused my my extra :, dealt with some reference issues, and massaged the math formatting.

**Comment by mcflugen** [comment]
@kbarnhart Is there any reason to wait to merge this before creating a new release (v2.1)?

**Comment by kbarnhart** [comment]
@mcflugen sounds good. I don't think this is critical for the 2.1 release, but wouldn't hurt.

Thanks for making the release.

**Comment by mcflugen** [comment]
@kbarnhart, @pfeiffea @jonczuba *landlab* *v2.1.0* is now available and includes the *NetworkSedimentTransporter*! 🎉

Thank you for this contribution!

**Comment by pfeiffea** [comment]
🎉 indeed!!

**Pull request merged**
