### PR TITLE
remove pit present logic

### PR DESCRIPTION
**Pull request by kbarnhart**
Addresses #1276 

It is not slick in that it doesn't identify a way to decide whether it is necessary to run the depression finder, but it fixes the errors induced in terrainbento.

### CODE REVIEW

**Comment by kbarnhart** [comment]
Improved to only run depression finder if there are pits OR if there are any nodes labeled anything other than _UNFLOODED.

I had to move some imports around to deal with circular import issues between FlowAccumulator and DepressionFinderAndRouter. @mcflugen please advise if you think there is a better way to do this. Perhaps something like the node status files?

Locally terrainbento's issues are fixed on with these changes. 

Should address concerns about whether or not to run the depression finder for efficiency issues. @gregtucker

**Comment by kbarnhart** [comment]
@mcflugen it looks like CI is hanging. Is there anything I need to do?

@mcflugen and @gregtucker I think this is ready to be considered for merging.

**Comment by mcflugen** [comment]
@kbarnhart You're all good. Some of the tests are failing because of a syntax error in one of the yaml files. I thought I had already fixed it but, unfortunately, I guess I hadn't and it got merged into *master*, which is why you're seeing it here. Anyway, I've fixed the syntax error and, I believe, all of the tests should run now.

**Comment by kbarnhart** [comment]
@mcflugen got it thanks! What do you think about how I handled the import of the flood code status (e.g. _FLOODED). Its not elegant, but it solved the circular import issues I was having.

**Comment by mcflugen** [comment]
@kbarnhart I suspect that the circular import errors were because you were using absolute imports rather than relative. I know this is common in our components but it's something we should probably go through and change.

Instead of defining the flood codes in `__init__.py` maybe define them within the depression finder? Maybe in a *floodstatus.py* file (like we do with node status)?
```python
from enum import IntEnum, unique


@unique
class FloodStatus(IntEnum):
    """Codes for depression status"""

    UNFLOODED = 0
    PIT = 1
    CURRENT_LAKE = 2
    FLOODED = 3
```
The flow accumulator could then import them like,
```python
from ..depression_finder.floodstatus import FloodStatus
```

**Comment by kbarnhart** [comment]
@mcflugen I've attempted to implement the `depressionstatus.py` approach... but seem to be in relative import purgatory... Maybe you can see something I can't see. 🆘 

I get the following errors
```
(landlab_dev) barnhark@Katherines-MBP landlab % pytest
====================================================== test session starts =======================================================
platform darwin -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /Users/barnhark/opt/anaconda3/envs/landlab_dev/bin/python
cachedir: .pytest_cache
rootdir: /Users/barnhark/projects/landlab/landlab, configfile: pyproject.toml, testpaths: notebooks, landlab, tests
plugins: datadir-1.3.1, cov-2.11.1
collected 0 items / 1 error

============================================================= ERRORS =============================================================
_________________________________________________ ERROR collecting test session __________________________________________________
Traceback (most recent call last):
  File "/Users/barnhark/opt/anaconda3/envs/landlab_dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/barnhark/opt/anaconda3/envs/landlab_dev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/barnhark/projects/landlab/landlab/tests/components/depression_finder/conftest.py", line 5, in <module>
    from landlab.components import DepressionFinderAndRouter, FlowAccumulator
  File "/Users/barnhark/projects/landlab/landlab/landlab/components/__init__.py", line 2, in <module>
    from .depression_finder import DepressionFinderAndRouter
  File "/Users/barnhark/projects/landlab/landlab/landlab/components/depression_finder/__init__.py", line 1, in <module>
    from .lake_mapper import DepressionFinderAndRouter
  File "/Users/barnhark/projects/landlab/landlab/landlab/components/depression_finder/lake_mapper.py", line 14, in <module>
    from ..flow_accum import flow_accum_bw
  File "/Users/barnhark/projects/landlab/landlab/landlab/components/flow_accum/__init__.py", line 6, in <module>
    from .flow_accumulator import FlowAccumulator
  File "/Users/barnhark/projects/landlab/landlab/landlab/components/flow_accum/flow_accumulator.py", line 28, in <module>
    from ..depression_finder.floodstatus import FloodStatus
ModuleNotFoundError: No module named 'landlab.components.depression_finder.floodstatus'
======================================================== warnings summary ========================================================
../../../opt/anaconda3/envs/landlab_dev/lib/python3.8/site-packages/_pytest/config/__init__.py:1183
  /Users/barnhark/opt/anaconda3/envs/landlab_dev/lib/python3.8/site-packages/_pytest/config/__init__.py:1183: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
==================================================== short test summary info =====================================================
ERROR  - ModuleNotFoundError: No module named 'landlab.components.depression_finder.floodstatus'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 1 warning, 1 error in 2.07s ===================================================
```

**Comment by mcflugen** [comment]
@kbarnhart I think the only issue was that *depressionstatus.py* needed to be renamed to *floodstatus.py*.

**Comment by kbarnhart** [comment]
🤦 thanks @mcflugen

**Comment by kbarnhart** [comment]
@gregtucker I think this is finally ready for any comments you might have. Zero rush.

**Review by gregtucker — APPROVED** [review]
Looks good to me!

**Comment by kbarnhart** [comment]
@mcflugen I'm going to merge this and then open an issue proposing a new minor version.

**Pull request merged**
