### PR TITLE
remove conda-forge channel from environment-dev.yml

### PR DESCRIPTION
**Pull request by kbarnhart**
@amanaster2 has brought to our attention an install issue that this may fix. Either way, since we now use pip for the dev environment, it is redundant.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mcflugen if this passes, I think its OK to merge, right? 

nowhere do we truly test this environment (we just use the various `requirements-xxx.txt` files for travis and appveyor...)

Do you think we need to test this file?

@amanaster2 and @gregtucker I've added text as we discussed on the call, might you review it?

**Comment by kbarnhart** [comment]
:wave: @mcflugen @amanaster2 @gregtucker

**Comment by mcflugen** [comment]
@kbarnhart We could test this file but I'm not sure it would be worth the longer build times. What do you think?

I don't see why this can't be merged.

**Comment by kbarnhart** [comment]
agreed. merging.

**Pull request merged**
