### PR TITLE
Update setup.py for enhanced compilation of cython files #1467 Version 2

### PR DESCRIPTION
**Pull request by sebastien-lenard**
Spinoff of pull request #1468.

Contains a new implementation of the compilation of cython files according https://github.com/landlab/landlab/issues/1467. Features:
- The compilation can be parameterized at the  file levels with # instructions at the top of the .pyx file. (This presently doesn't work).
- The compilation can include other directories (and subs) than landlab. Here it includes the directory tests.
- The compilation is done with Python 3 and include docstrings

This request includes a use case with .pyx files and test .pyx and py files. (These files are required for the development of the FlowRouter which will follow.

This spinoff follows discussions with @mdpiper  and @mcflugen that highlight it may be preferable to keep the setup.py file as small as possible, without calling yaml library.

### CODE REVIEW

**Comment by mcflugen** [comment]
@sebastien-lenard Thanks for this. I made a few minor changes to *setup.py*.

**Comment by sebastien-lenard** [comment]
@mcflugen I still have a problem with your version of setup.py, which includes hidden directories and makes break my compilation on jupyterhub. This is why I added the line:
```
_dirs[:] = [d for d in _dirs if not d[0] == "."]
```

**Comment by mcflugen** [comment]
> @mcflugen I still have a problem with your version of setup.py, which includes hidden directories and makes break my compilation on jupyterhub.

Interesting. I have not seen that before. Where do the hidden folders containing *.pyx* files come from on the JupyterHub?

**Comment by sebastien-lenard** [comment]
> > @mcflugen I still have a problem with your version of setup.py, which includes hidden directories and makes break my compilation on jupyterhub.
> 
> Interesting. I have not seen that before. Where do the hidden folders containing _.pyx_ files come from on the JupyterHub?

@mcflugen each time there's a compile error, this generate a .ipynb_checkpoints directory (in each subdirectory where the compilation failed. I'm not sure the directory is generated when compilation succeeds.

**Comment by mcflugen** [comment]
> @mcflugen each time there's a compile error, this generate a .ipynb_checkpoints directory (in each subdirectory where the compilation failed. I'm not sure the directory is generated when compilation succeeds.

Are you compiling the extensions from within a Jupyter notebook rather than from a terminal?

**Comment by sebastien-lenard** [comment]
> > @mcflugen each time there's a compile error, this generate a .ipynb_checkpoints directory (in each subdirectory where the compilation failed. I'm not sure the directory is generated when compilation succeeds.
> 
> Are you compiling the extensions from within a Jupyter notebook rather than from a terminal?

@mcflugen I compile via a console, under a copy of the csdms environment, either using python setup.py build_ext --inplace or pip install -e .

**Comment by sebastien-lenard** [comment]
@mcflugen clang compilation on macos fails (Test / Run the tests (macos-latest, 3.10) (pull_request) ), apparently because compilation is under an older version of c++ and c++11. I can try to force it through compilation arguments, but maybe there's an explanation for this difference between windows/ubuntu and macos?

**Review by sebastien-lenard — COMMENTED** [review]
All changes concern new files, except setup.py. This file has been edited by @mcflugen and reviewed + tested locally by me. Everything seems correct.

**Pull request merged**
