### PR TITLE
Gt/add green ampt ttl

### PR DESCRIPTION
**Pull request by gregtucker**
Add a short tutorial notebook for the `SoilInfiltrationGreenAmpt` component. Also modifies the header docstring for the component.

### CODE REVIEW

**Comment by gregtucker** [comment]
@frengers any comments on this tutorial for Green Ampt?

It's pretty minimal but I thought it better to have something than nothing. Happy to see others add material to the tutorial if so inspired.

**Comment by gregtucker** [comment]
@gantian127 could you give this a review?

**Comment by gantian127** [comment]
@gregtucker Will do. Thanks!

**Comment by frengers** [comment]
@gregtucker I realize this is such a newb question, but I can figure out how to find/access the link to the notebook.

**Comment by gantian127** [comment]
@gregtucker I tested the notebook and it worked as expected. Thanks!

**Comment by gregtucker** [comment]
Thanks @gantian127 

@frengers good question! It's not totally obvious. One option is to clone the repository including this branch. Or just grab a copy of the notebook by copying the raw contents of the file (the JSON that represents the notebook), pasting it into a text editor, and saving as an .ipynb file.

For now, since @gantian127 has reviewed it and the tests pass, I'm going to go ahead and merge, but please let me know if you have comments/suggestions, and I can open a new PR to address them.

**Pull request merged**
