### PR TITLE
Add dy to RasterModelGrid

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds a `dy` attribute to `RasterModelGrid` so that the row spacing (*dy*) can be different than the column spacing (*dx*). The "new-style" way of creating a raster grid is:
```python
grid = RasterModelGrid((4, 5), spacing=(4, 5))
```
*spacing* is a tuple of *(dy, dx)*. Notice that the shape of the grid is given as a tuple of *(nrows, ncols)*. The "old-style" should still work, though.

Most of the changes are in `landlab/grid`. I didn't touch much in the components folder. All of the components still assume that `dx == dy`.

I still need to fix `force_boundaries_from_gradients`. It seems to only be used by a deprecated method (`set_fixed_gradient_boundaries`, which isn't used anywhere) so it may not be worth fixing and, perhaps, should be removed. @SiccarPoint, your initials are on this method. Do you have any thoughts?

Deprecated:
- `node_spacing`: this should no longer be used. Use `dy` or `dx` instead. This now raises `RuntimeError` if it's called when `dx != dy`.

Removed:
- `node_spacing_vertical`: Use `grid.dy` instead.
- `node_spacing_horizontal`: Use `grid.dx` instead.

### CODE REVIEW

**Comment by SiccarPoint** [comment]
Delete both `force_boundaries_from_gradients` and `set_fixed_gradient_boundaries`, by all means.

I just swept the Components folder for dodgy dx==dy assumptions. I got all mine I think, but found a couple of places where Jordan and Sai had done it. I'm making an Issue for this right now.

**Comment by mcflugen** [comment]
Perfect. Thanks! I'll remove those functions.

Feel free to include your changes of your components relating to `dy != dx` in this pull request.

**Comment by saisiddu** [comment]
I am not able to merge this pull request. It says that there is a conflict where I haven't edited anything. @mcflugen , @SiccarPoint : Any suggestions?

**Comment by mcflugen** [comment]
Don't worry about it. I'll rebase so that you can merge it without conflicts.

**Comment by mcflugen** [comment]
Well I made a royal mess of that rebase! In any case, the tests are passing now and it should be able to be merged just fine.

**Comment by saisiddu** [comment]
@mcflugen : So, are you going to merge this? I can do the review again if you want. I still see a conflict issue and I am guessing you are taking care of the issues pointed out by @SiccarPoint .

**Comment by mcflugen** [comment]
Sure. I'll merge it. The conflicts are because I pushed the fix for Dan's problem to master.

**Pull request merged**
