### PR TITLE
Merge master into release

### PR DESCRIPTION
**Pull request by kbarnhart**

### CODE REVIEW

**Comment by kbarnhart** [comment]
Do you understand why this doesn't see the prior merge I made on #1187. Is it because that was a squash merge?

How do you think I should handle this so that in the future its is cleaner?

**Comment by mcflugen** [comment]
@kbarnhart Not sure why this doesn't see your prior merge. I couldn't definitely be wrong, but I don't think it would be because of the squash merge.

**Comment by mcflugen** [comment]
@kbarnhart I see the Travis build failed in the testing-the-docs-stage with a broken link. I'm going to go ahead and treat that as a pass.

Looks good! 👍

**Comment by kbarnhart** [comment]
Would you squash-merge this? Or one of the other options?

**Comment by mcflugen** [comment]
Yay! 🎉

**Pull request merged**
