### PR TITLE
Address Units/Dimensions

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR implements what was discussed on #1104. I've prioritized this because it is discussed in the paper (which I plan to submit by the end of the week). 

Specifically it:

* Add a _unit_agnostic = None to component base class, then add _unit_agnostic = False to those components for which it really matters, and _unit_agnostic = True where it doesn't matter.
* Add public attribute to Component. Add information to info printed about component
* Add information to the Component tutorial.
* Adds a page to the user guide which describes how landlab deals with units. 

Where I observed a unit conversion within a component (in the init/run/other calculation) I wrote unit_agnostic=False. Based on my perusal, the components for which this is the case are: 

GroundwaterDupuitPercolator
KinwaveImplicitOverlandFlow
KinwaveOverlandFlowModel
LandslideProbability
LateralEroder
OverlandFlow
OverlandFlowBates
PotentialEvapotranspiration
PotentialityFlowRouter
Radiation
SedDepEroder
SoilMoisture
SoilInfiltrationGreenAmpt
SpatialPrecipitationDistribution
VegCA
Vegetation

If others could please look at these components and indicate whether they agree/disagree that would be much appreciated. 

I also observed something that is (sorta) troubling... There are cases in which the only reason a component is unit agnostic is that there is an inconsistency between units of different inputs (this is the case in the KinwaveOverlandFlowModel component highlighted in the "making components" tutorial.... This occurs because Mannings N is specified as s/m^(1/3) but precipitation and infiltration rates are specified with time units of hours...

I would argue that we should look for cases like these and remove all of them (but I'm probably over reacting). 

The other main reason that a component is non-unit-agnostic is that there is a non-user-defined coefficient that has units.

tagging @landlab/core

### CODE REVIEW

**Comment by saisiddu** [comment]
@kbarnhart: I agree with PotentialEvapotranspiration, Radiation, SoilMoisture,  VegCA, and Vegetation. I am pretty sure LandslideProbability is also NOT unit agnostic (agreeing with your decision). Thank you!

**Comment by DavidLitwin** [comment]
@kbarnhart the shear stress method in the groundwater component may be the only thing that's unit  dependent (SI), because it relies on Manning's equation. For everything else, while I've given default values in SI (m and s), there's no reason why it couldn't be in ft or hr, so long as units were consistent (elevations, grid spacing, hydraulic conductivity and recharge).

**Comment by DavidLitwin** [comment]
Also @kbarnhart, this may be up for debate, but I'm not sure the shear stress calculation even belongs in gdp? It was useful to me at one point, but it (a) does not depend on flow being created with the groundwater component (b) depends on a running a FlowAccumulator.

**Comment by nathanlyons** [comment]
@kbarnhart I did not find a unit agnosticism that I disagreed with.

**Pull request merged**
