### PR TITLE
Remove unused files

### LINKED ISSUE #1533: Remove stale files
There are number of stale files, mostly configuration files from services we no longer use, in the top-level directory of the Landlab repository. These include:

- .codeclimate.yml
- .gitattributes
- .gitmodules
- .travis.yml
- Makefile
- conftest.py

These unused files should be removed.

### PR DESCRIPTION
**Pull request by mdpiper**
### Description

There are a few files in the top-level directory of the Landlab repository that are no longer used, including configuration files from services (`.codeclimate.yml`, `.travis.yml`), Git configuration files (`.gitattributes`, `.gitmodules`), and the `Makefile` obsoleted by the switch to *nox*. This PR removes these files.

Also, two Actions configuration files were recently renamed, which broke badge links in the README. These links have been repaired.

This fixes #1533. 

### Checklist - did you ...

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by mcflugen** [comment]
Thanks @mdpiper. I had left the *Makefile* around only because @BCampforts liked to type `make pretty` but I think it's time he let go of the past and embrace *nox*.

**Comment by mdpiper** [comment]
@mcflugen We're forward-looking people. Sadly, we have to leave dinosaurs like @BCampforts in the past.

**Comment by BCampforts** [comment]
I learned to embrace the beauty of the past from giants: my good friends Marcosaurus 🦖 and Ericosaurus 🦕

**Comment by mdpiper** [comment]
@mcflugen Give me a 👍 and I'll merge this!

**Review by mcflugen — APPROVED** [review]
👍

**Pull request merged**
