### PR TITLE
Add more linters and remove more lint

### PR DESCRIPTION
**Pull request by mcflugen**
### Description

This pull request adds additional linters to *Landlab* and removes additional lint.

Although pretty much every file was touched, nearly all of the changes are trivial.

Most of the removed lint includes things like,
* trailing white space
* files end in one and only one newline
* clean up yaml and toml files

Other lint includes things like,
* removing unused loop counters
* combining nested *if* statements—for some reason there were *a lot* of these
* upgrading to Python 3.8+ syntax

Some more substantial lint included,
* removing mutable objects as keyword defaults
* replacing the *lru_cache* decorator on method functions with *cached_property*—*lru_cache* can result in significant memory leaks.

Things I haven't done in the pr but that should be done in another,
* Remove large files from the repository (and its history)
* Check for docstring lint
* Run a static type check linter (i.e. mypy) over the code

### Checklist - did you ...

- [x] Add a [news fragment](https://landlab.readthedocs.io/en/master/development/contribution/index.html#news-entries) file entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?
- [x] All tests have passed?
- [x] Formatted code with black?
- [x] Removed lint reported by flake8?
- [x] Sucessful documentation built? (if documentation added or modified)

### CODE REVIEW

**Comment by mdpiper** [comment]
Which tool is combining the nested *if* statements? That's pretty neat. It's also inverting the logic in other *if* statements to remove an *else* clause.

**Comment by mcflugen** [comment]
> Which tool is combining the nested if statements? That's pretty neat. It's also inverting the logic in other if statements to remove an else clause.

That tool is me. *flake8-simplify* only identified those issues.

**Comment by mdpiper** [comment]
Wow, that *me* tool is really good!

**Review by mdpiper — APPROVED** [review]
It feels good to remove lint.

**Pull request merged**
