### PR TITLE
Lake routing

### PR DESCRIPTION
**Pull request by SiccarPoint**
Time for a test out of our new system! This pull request implements flow routing for the lake_mapper module, so that flow can be routed across depressions. Tests are present.

### CODE REVIEW

**Comment by jadams15** [comment]
Ok, I see this was assigned to me! I'll wait until the tests are finished and I'll review the code.

**Comment by mcflugen** [comment]
Wonderful! Thanks, Dan. This looks good.

A few things.
* Docstrings should by numpydoc style (so, "Parameters", not "Tasks").
* Use `BAD_INDEX_VALUE`, not 2147483647, as the max int will vary on different machines.
* `three_pits` should be `test_three_pits` so that it's run as a unit test?
* For author, maybe use the Sphinx `codeauthor` or `sectionauthor` directives?
* Move example code (`test_lake_mapper.py`) into our examples repository?
* PEP8 stylings.

**Comment by SiccarPoint** [comment]
2) Blame Greg for this. I imported BAD_INDEX_VALUE as XX like a good boy.
4) Not sure. Do we really want our email addresses exposed to web crawlers via github?
5) Can do, but will need cleaning. It can certainly also stay where it is in current form. Leaving it for now.

**Comment by mcflugen** [comment]
* Cool. Blaming @gregtucker. Bad @gregtucker!
* Can we just not include the email address or use the general landlab one (which doesn't exist yet)? Or, since git keeps track of all our edits maybe we don't need anything.
* Sounds good. Since it's under `examples` it's not run as part of the unit tests, anyway.

**Comment by SiccarPoint** [comment]
Re PEP8 - If I have a docstring with a really long line, I can’t both make the docstring work and also stay PEP8 compliant. e.g., 

>>> from landlab.components.flow_routing.lake_mapper import DepressionFinderAndRouter

…is already more than 79 chars. There are many examples.

What’s best practice?

D

**Comment by SiccarPoint** [comment]
Closing because I have screwed up my version management. Opening another imminently.

**Comment by mcflugen** [comment]
For long doctests, if the command line is too long use parens and `...` to continue onto the next line. For example,

``` python
>>> from landlab.components.flow_routing.lake_mapper import (
...     DepressionFinderAndRouter)
```

If the return string is too long, use the `NORMALIZE_WHITESPACE` option. For example,

``` python
>>> rmg.status_at_node # doctest : +NORMALIZE_WHITESPACE
array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      dtype=int8)
```
or even,
``` python
>>> rmg.status_at_node # doctest : +NORMALIZE_WHITESPACE
array([1, 1, 1, 1, 1,
       1, 0, 0, 0, 1,
       1, 0, 0, 0, 1,
       1, 1, 1, 1, 1],
      dtype=int8)
```

**Comment by SiccarPoint** [comment]
Cool.

I have a feeling that there’s some issue on my local machine with the parsing of the NORMALIZE_WHITESPACE option. I’ll look into it.

D

**Comment by SiccarPoint** [comment]
Cool.

I have a feeling that there’s some issue on my local machine with the parsing of the NORMALIZE_WHITESPACE option. I’ll look into it.

D

**Pull request closed without merging**
