### PR TITLE
SiccarPoint/modernise components

### PR DESCRIPTION
**Pull request by SiccarPoint**
This is a bit of a beast. Reflects numerous updates to the style of components I have built.

Additionally, it corrects problems in the patch data for irregular grids, which may soon be superseded by the graphs merge.

### CODE REVIEW

**Comment by SiccarPoint** [comment]
I should note there are almost certainly going to be some errors related to gFlex import here, but I need to see them on a machine without gFlex on it before I can debug them...

**Comment by SiccarPoint** [comment]
The gFlex issues should now be resolved.

**Comment by mcflugen** [comment]
This looks great! This is my kind of pull request. Lots of code removals, lots of new tests, and, best of all, lots of nit-picky PEP8 formatting fixes!

**Comment by SiccarPoint** [comment]
I love those PEP8 fixes, probably too much. STOP ME BEFORE I FORMAT AGAIN!!!!!!!

**Pull request merged**
